### ISSUE TITLE
Querying ListRelationTuples with any subject results in row being added to keto_uuid_mappings

### ISSUE THREAD

**Issue by rdurell** [ory/keto#1076]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

Querying ListRelationTuples with an unknown subject results in row being added to keto_uuid_mappings.  Beyond just database bloat, this is a potential DOS attack vector.  Something along the lines of repeatedly querying the endpoint with a randomly generated subject could fill up storage leading to a DOS

### Reproducing the bug

1. Run keto serves with a persistent store (mysql or postgres)
2. Query the keto_uuid_mappings table directly for a subject not already persisted as a relationship tuple.  A random uuid would work well.
`select id, string_representation  from public.keto_uuid_mappings where string_representation = '940099dd-fc53-5c7f-a684-98c05e4bdca6'`
**Note that there are no rows returned**
3. Using the keto cli, execute a relation-tuple get command for a valid namespace and the unknown subject used above.
`keto relation-tuple get --namespace books --subject-id 940099dd-fc53-5c7f-a684-98c05e4bdca6`
**Note that no tuples are returned**
4. Query the keto_uuid_mappings table directly for the subject used above.
`select id, string_representation  from public.keto_uuid_mappings where string_representation = '940099dd-fc53-5c7f-a684-98c05e4bdca6'`
**Note that a single row is now returned**

Expected: No rows would be added.
Actual: A row was added for the unknown subject.

### Version

0.10.0-alpha.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

**Comment by KiNgMaR** [comment]
+1

Context: we are trying to use keto in "read only mode" and have therefore connected it to a read-only MySQL slave. This behavior breaks the approach.

**Comment by zepatrik** [comment]
Yes, this should not happen.
