### ISSUE TITLE
cannot import policies with regex

### ISSUE THREAD

**Issue by flasaracina** [ory/keto#113]
**Describe the bug**
when `keto engines acp ory policies import` is used against a JSON document representing a policy it fails to retain the angle brackets that are needed when using the `regex` flavor.

**Reproducing the bug**
Just run the example in the example repository using a resource policy like the following:

```json 
[{
  "id": "some-id",
  "description": "some description",
  "subjects": ["some-subject"],
  "effect": "allow",
  "resources": [
      "resource:sample:<.*>",
  ],
  "actions": [
      "action:sample:<.*>:foo",
  ]
}]
```
setup an oathkeeper policy that asks for a resource and an action that leverage those regular expressions.

**Expected behavior**
I expect to be able to access the resource. If you check how the policy was saved in the database, you'll see that those angle brackets have been escaped preventing, I guess, Ladon to parse the rule correctly.

When keto is importing the JSON document, as per GO policy when marshaling a JSON string, it will escape any HTML character, thus causing the unwanted behavior shown above.

Thanks

**Comment by aeneasr** [comment]
Oh interesting, weird that this did not come up in the tests. Could you write a failing test case maybe and open a PR?

**Comment by flasaracina** [comment]
I'd like to do so, but I cannot do it anytime soon, unfortunately. Anyway, looking at the test stubs it is clear why the test passes seamlessly: in those JSON files there is no rule defined with a glob nor a regex path whatsoever. So adding a test for those use cases would be as simple as adding a new policy to the file, like so:

```json
{
    "id": "policy-regex",
    "subjects": [
      "peter-2",
      "group-2"
    ],
    "resources": [
      "resources-<.*>",
    ],
    "actions": [
      "actions-<.*>"
    ],
    "effect": "allow"
}
```
As they are now, those tests just checks if those policies get saved in the right collection.

Again, I am sorry if I cannot open a PR about it right now. I'll try to do it when I get the time.

Thanks

**Comment by flasaracina** [comment]
Quick update: glob pattern matching is working as expected so I'll stick with it while waiting for a solution.

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
