### ISSUE TITLE
Error: context deadline exceeded

### ISSUE THREAD

**Issue by mjolk** [ory/keto#1133]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

While integrating keto i could for the life of me not get the cli client to connect to the running keto service to seed with initial tuples.
After hours of bashing my head against the wall (thinking it had to do with docker networking or other) i just tried the cats video example and lo and behold : the same error...
I'm running contrib/cat.../up.sh from source root. Installed keto checked out on tag v0.10.0-alpha.0.

```
Error: context deadline exceeded
Usage:
  keto relation-tuple create <relation-tuple.json> [<relation-tuple-dir>] [flags]

Flags:
      --format string                         Set the output format. One of table, json, yaml, and json-pretty. (default "default")
  -h, --help                                  help for create
      --insecure-disable-transport-security   Disables transport security. Do not use this in production.
      --insecure-skip-hostname-verification   Disables hostname verification. Do not use this in production.
  -q, --quiet                                 Be quiet with output printing.
      --read-remote string                    Remote address of the read API endpoint. (default "127.0.0.1:4466")
      --write-remote string                   Remote address of the write API endpoint. (default "127.0.0.1:4467")

Global Flags:
  -c, --config strings   Config files to load, overwriting in the order specified. (default [/home/mjolk/keto.yml])

context deadline exceeded
```
either i'm overlooking something or the grpc api is broken somewhere, mismatch versions proto? No idea.Seems the client (keto cli) cannot connect and times out.
the http api seems to be working.

### Reproducing the bug

Just try the cats example in contrib on v0.10.0-alpha.0, but i also have an entire setup with posgresql db etc which works fine until i try to run keto client to insert tuples. See above context timeout error.

### Version

v0.10.0-alpha.0

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Other

**Comment by fishstamp82** [comment]
What happens if you add `--insecure-disable-transport-security` ? For me I had the same above issue until I disabled the tls option.

**Comment by gousse** [comment]
> 

same issue here, I confirm adding the insecure option solve the issue
```
 $ keto relation-tuple create relation-tuples --insecure-disable-transport-security
NAMESPACE	OBJECT		RELATION NAME	SUBJECT				
videos		/cats/1.mp4	owner		videos:/cats#owner		
videos		/cats/1.mp4	view		videos:/cats/1.mp4#owner	
videos		/cats/1.mp4	view		*				
videos		/cats/2.mp4	owner		videos:/cats#owner		
videos		/cats/2.mp4	view		videos:/cats/2.mp4#owner	
videos		/cats		owner		cat lady			
videos		/cats		view		videos:/cats#owner	
```

**Comment by gousse** [comment]
another test:

```
$ keto status
NOT_SERVING
$ keto status --insecure-disable-transport-security
SERVING
```

demo script should be patched for basic tests and solution discovery

**Comment by gousse** [comment]
```
$ cat up.sh
```
patched demo script:
```
#!/bin/bash
set -euo pipefail

keto serve -c contrib/cat-videos-example/keto.yml &
keto_server_pid=$!

function teardown() {
    kill $keto_server_pid || true
}
trap teardown EXIT

export KETO_WRITE_REMOTE="127.0.0.1:4467"

keto relation-tuple create contrib/cat-videos-example/relation-tuples --insecure-disable-transport-security

echo "

Created all relationships. Now you can use the Keto CLI client to play around:

export KETO_READ_REMOTE=\"127.0.0.1:4466\"
keto relation-tuple get videos
keto check \"*\" view videos /cats/1.mp4
keto expand view videos /cats/2.mp4
"

keto expand view videos /cats/2.mp4 --insecure-disable-transport-security

# sleep 10h; has to be defined like this because OSX does not know units https://www.unix.com/man-page/osx/1/sleep/
sleep 36000

```

**Comment by hperl** [comment]
Thanks for the report and the analysis! @gousse, do you want to create a PR to patch the demo script?

Further, we should use this issue to improve the error message on an insecure transport. @mjolk, do you agree?

**Comment by gousse** [comment]
yes no pbl, I've done https://github.com/ory/keto/pull/1158

**Comment by mjolk** [comment]
Allright, i thought i tried that already. Didn't get the chance to test it yet but looks like the obvious problem. It's also stated in the docs so my bad. Thanks!
