### ISSUE TITLE
Ory Permission Language: support Array syntax

### ISSUE THREAD

**Issue by nidomiro** [ory/keto#1134]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

The Ory Permission Language currently supports arrays using the `[]` syntax.
Some users (or linter) prefer to use the `Array<>` Syntax but it's currently not supported.

### Describe your ideal solution

Also allow `Array<User | SubjectSet<Group, "members">>` as valid Syntax for `(User | SubjectSet<Group, "members">)[]`

### Version

Ory Network (15.11.2022)

**Comment by hperl** [comment]
I was hesitant if we want to diversify the syntax, but I think in this case it is a nice addition. @zepatrik any objections? Do we need to adapt the types as well?

**Comment by zepatrik** [comment]
Everything should work as expected there.
