### ISSUE TITLE
SQL optimization: join UUID mapping on relation tuples when required

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#1197]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [X] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Currently we first query the tuples and then do a second query for mapping the UUIDs. 

### Describe your ideal solution

Depending on the API (list & expand) we should be able to apply the mapping on the database by joining the UUID mapping table onto the relation tuple table.

### Workarounds or alternatives

Keep as is.

### Version

master

**Comment by hperl** [comment]
I also thought about this. Continuously joining with the mapping table, especially if it has a different storage class in cockroach, will be very expensive.

Alternatively, we could add columns for the unmapped fields directly into the relation tuples table, and add another book field to tuples creation to identify a tuple as containing PII. If set, the premapped data will be written to the mapping table, as it is now. If unset, the unmapped data will be stored in the relation tuples table.

Unmapping means looking in the unmapped columns first, the mapping table second.

This way we have
- fast lookups for non PII tuples
- data optionally stored in a specific region for PII tuples, at the cost of performance 

WDYT?

**Comment by zepatrik** [comment]
> Continuously joining with the mapping table, especially if it has a different storage class in cockroach, will be very expensive.

I suggest we measure this first before we go the more complex route you sketched :wink:

**Comment by hperl** [comment]
Agreed, we can simply run the queries against a multi-region CRDB.
