### ISSUE TITLE
Unexpected DoOryAccessControlPoliciesAllow results in Go SDK

### ISSUE THREAD

**Issue by jrmullins** [ory/keto#122]
**Describe the bug**

Performing a `DoOryAccessControlPoliciesAllow` check with the Go SDK, where the expected `allowed` value is false, returns a nil `DoOryAccessControlPoliciesAllowOK` and an error that can be type asserted into a `DoOryAccessControlPoliciesAllowForbidden`.

I am not sure if this is by design but it felt awkward to me.

**Reproducing the bug**

Run Keto locally and run the following code:

```
package main

import (
	"fmt"
	"log"
	"os"
	"time"

	"github.com/ory/keto/sdk/go/keto/client"
	"github.com/ory/keto/sdk/go/keto/client/engines"
	"github.com/ory/keto/sdk/go/keto/models"
)

func main() {
	// Connect to Keto
	config := &client.TransportConfig{
		Host:     "localhost:4466",
		BasePath: client.DefaultBasePath,
		Schemes:  []string{"http"},
	}
	client := client.NewHTTPClientWithConfig(nil, config)

	// Check connection
	ok, err := client.Health.IsInstanceAlive(nil)
	if err != nil {
		panic(err)
	}
	log.Println(ok.Payload.Status)

	// Create policy thats expected to not be allowed
	input := &models.OryAccessControlPolicyAllowedInput{
		Subject:  "foo",
		Action:   "bar",
		Resource: "baz",
	}
	params := &engines.DoOryAccessControlPoliciesAllowParams{
		Body:   input,
		Flavor: "regex",
	}
	params.WithTimeout(30 * time.Second) // We have to do this every time?

        // Check Allowed (should be false)
	allowOk, err := client.Engines.DoOryAccessControlPoliciesAllow(params)
	if err != nil {
                // Cast error?
		t, ok := err.(*engines.DoOryAccessControlPoliciesAllowForbidden)
		if !ok {
			panic("can't cast err to DoOryAccessControlPoliciesAllowForbidden")
		} else {
			log.Println("success? casted err to struct", *t.Payload.Allowed) // Why???
			os.Exit(0)
		}
		panic(fmt.Sprintf("some other error occured %+v\n", err))
	}
	log.Println("everything is ok", *allowOk.Payload.Allowed)
}
```

**Expected behavior**

I would expect `DoOryAccessControlPoliciesAllow` to return a `DoOryAccessControlPoliciesAllowOK` with a `Payload` (models.AuthorizationResult) `Allowed` value to be `false`.

**Environment**

* Version: master/571b447ed3a02f43623ef5c5adc09682b5f379bd
* Environment: go version go1.12.1 darwin/amd64

**Comment by aeneasr** [comment]
Ah yeah that's unfortunately a limitation of the code-generated SDK. We do indeed send a 403 forbidden if allowed is false, because that's what some API Gateways expect

**Comment by jrmullins** [comment]
Ok thats fine, I'll close this issue. Thanks for verifying!
