### ISSUE TITLE
Removing member from role fails with `unknown error (status 200)`

### ISSUE THREAD

**Issue by morningvera** [ory/keto#127]
**Describe the bug**

Attempting to remove a member from a role fails with `unknown error (status 200)`.

**Reproducing the bug**

1. Start Keto v0.3.3-sandbox using the ORY guide: https://www.ory.sh/docs/keto/configure-deploy
2. Create a role with a member via the SDK (creating a role with no members works too)
3. Try removing that member from the role
4. Request fails with response: `unknown error (status 200): {resp:0xc0000ac1b0}`

```
package main

import (
	"github.com/ory/keto/sdk/go/keto/client"
	"github.com/ory/keto/sdk/go/keto/client/engines"
	"github.com/ory/keto/sdk/go/keto/models"
)

func main() {
	ketoClient := client.NewHTTPClientWithConfig(nil, &client.TransportConfig{
		Host:     "localhost:4466",
		BasePath: "",
		Schemes:  []string{"http"},
	})

	createReq := engines.NewUpsertOryAccessControlPolicyRoleParams().
		WithFlavor("regex").
		WithBody(&models.OryAccessControlPolicyRole{
			ID:      "test-role",
			Members: []string{"test@example.com"},
		})
	_, err := ketoClient.Engines.UpsertOryAccessControlPolicyRole(createReq)
	if err != nil {
		panic(err)
	}

	removeReq := engines.NewRemoveOryAccessControlPolicyRoleMembersParams().
		WithFlavor("regex").
		WithID("test-role").
		WithMember("test@example.com")
	_, err = ketoClient.Engines.RemoveOryAccessControlPolicyRoleMembers(removeReq)
	if err != nil {
		panic(err)
	}
}
```

**Expected behavior**

The SDK should handle the valid request and return an empty response. Which status code is correct: `201 created` or `200 ok`? Probably an easy fix either way (I can submit a PR for it if needed).

**Environment**

* Version: v0.3.3-sandbox
* Environment: Docker

**Comment by aeneasr** [comment]
The proper response would be a 204 No Content - would you be up for a fix? :)

**Comment by morningvera** [comment]
Makes sense! Sure, I should be able to submit something soon.

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
