### ISSUE TITLE
Add support for read and write databases

### ISSUE THREAD

**Issue by diegobernardes** [ory/keto#1281]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Network](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe your problem

Databases like AWS Aurora have different endpoints for reads and writes and Keto could add support for using multiple database connections to improve scalability and latency.

### Describe your ideal solution

The database is configured like this:
```dsn: postgres://...```

And this is a suggestion of how it could be configured:
```
dsn:
  read: postgres://...
  write: postgres://...
```

### Workarounds or alternatives

None.

### Version

v0.10.0

**Comment by faraonc** [comment]
I don't think is a feature already implement/supported. Is there a way to achieve this without having to support 2 separate deploys of keto?
