### ISSUE TITLE
Allow multiple filter param values in roles and policies list API

### ISSUE THREAD

**Issue by sum2000** [ory/keto#134]
This is a continuation of #124. Currently, only one value can per filter param is supported in the list API. For example, current filter only allows queries like `/policies/member=foo&subject=bar`, but often times a user needs multiple value search like `policies/member=foo&member=baz&subject=bar`

This is easy to implement in the storage filter, but the question is what does it mean to pass multiple values? Does it mean AND or OR? I doubt it is possible to support both with the same url format. This REST spec does not provide any guideline for this. This page(https://stackoverflow.com/questions/1746507/authoritative-position-of-duplicate-http-get-query-keys) seems to suggest that the intended behavior is AND. 

What are your thoughts?

**Comment by wraix** [comment]
You can make arrays in urls with [] then the AND part would be clear as the array would contain the members. But the queries are hard to read.

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
