### ISSUE TITLE
glob not working on members of groups

### ISSUE THREAD

**Issue by zd9KgA** [ory/keto#135]
Wildcards in the members of groups are not interpreted as wildcards for flavor glob.

Applies to recent versions of keto, e.g., to commit db94481.

The reason seems to be at the end of the file *engine/ladon/rego/glob/main.rego* in the function *match_subjects*. The intended implementation is preceded by the implementation for the flavor exact.

Add something like

decide_allow([group_policy], [{"id": "groups:6", "members": ["group-*"]}]) with input as {"resource": "articles:6", "subject": "group-member", "action": "actions:6"}

to main_test.rego for a corresponding test.

**Comment by aeneasr** [comment]
nice find! would you be up for a fix? :)

**Comment by zd9KgA** [comment]
Thx. 

I can turn the suggested fix into a pull request. Before doing so, I'd like to run the tests, but apparently just running 

> go test .

does not do the job. Any hints on how to carry out the tests associated with keto?

**Comment by aeneasr** [comment]
Why does it not do the job? Can you show some output or logs please? Also what Go version are you using?

**Comment by zd9KgA** [comment]
Hi!

The test suite does not seem to be properly configured. But I'm new to Go, in fact, this is the first occasion I'm digging into go code, maybe I'm missing something. But at least my go setup has allowed me to build keto, oathkeeper, and hydra (and map the executables into Docker images).

Here we go for the rest of your questions:

> go version
> go version go1.12.9 linux/amd64


[...]/go/src/github.com/ory/keto$ git reflog
db94481 HEAD@{0}: checkout: moving from release/v1.0.0-beta.9 to master
2a7046b HEAD@{1}: checkout: moving from 2f620632d0375bf9c7e58dbfb49627c02c66abf3 to release/v1.0.0-beta.9
2f62063 HEAD@{2}: checkout: moving from master to v1.0.0-beta.9
db94481 HEAD@{3}: clone: from https://github.com/ory/keto
[...]/go/src/github.com/ory/keto$ go test github.com/ory/keto
?   	github.com/ory/keto	[no test files]
# and for the sake of completeness
[...]/go/src/github.com/ory/keto$ go test .
?   	github.com/ory/keto	[no test files]

**Comment by aeneasr** [comment]
The proper command is `go test ./...`. If you do not wish to include database tests (not required for this change IMO) you can do `go test -short ./...`

**Comment by zd9KgA** [comment]
That makes a difference, thanks. See below. 

But still I'm puzzled, as when I put syntactic nonsense into the file engine/ladon/rego/glob/main_test.go within the part labeled "test_allow_group_policy" there is no effect on the output. 

I did assume that the test cases listed in that file would somehow be consumed by the engine/ladon test. But I don't see how. And the fact that corrupting the file syntactically does not make a difference does not speak in favor of my assumption.

So, how can I test my changes?

?   	github.com/ory/keto	[no test files]
ok  	github.com/ory/keto/cmd	1.048s
?   	github.com/ory/keto/cmd/client	[no test files]
?   	github.com/ory/keto/cmd/server	[no test files]
?   	github.com/ory/keto/driver	[no test files]
?   	github.com/ory/keto/driver/configuration	[no test files]
?   	github.com/ory/keto/engine	[no test files]
ok  	github.com/ory/keto/engine/ladon	0.244s
?   	github.com/ory/keto/engine/ladon/rego	[no test files]
?   	github.com/ory/keto/engine/ladon/rego/condition	[no test files]
?   	github.com/ory/keto/engine/ladon/rego/core	[no test files]
?   	github.com/ory/keto/engine/ladon/rego/exact	[no test files]
?   	github.com/ory/keto/engine/ladon/rego/glob	[no test files]
?   	github.com/ory/keto/engine/ladon/rego/regex	[no test files]
?   	github.com/ory/keto/sdk/go/keto/client	[no test files]
?   	github.com/ory/keto/sdk/go/keto/client/engines	[no test files]
?   	github.com/ory/keto/sdk/go/keto/client/health	[no test files]
?   	github.com/ory/keto/sdk/go/keto/client/version	[no test files]
?   	github.com/ory/keto/sdk/go/keto/models	[no test files]
ok  	github.com/ory/keto/storage	(cached)
?   	github.com/ory/keto/x	[no test files]

**Comment by aeneasr** [comment]
Ah yeah, `go test` only tests the go code, not the actual policy code which is left to OPA. This is obviously very badly documented (not at all). Sorry about the inconvenience. I also realized that this is not being tested by our CI which is obviously a mistake. We do however test e2e if the policies are doing what they should.

To get rego tests to work, you have to [install OPA](https://www.openpolicyagent.org/docs/latest/#1-download-opa) and then run `opa test . -v` ([docs](https://www.openpolicyagent.org/docs/latest/policy-testing/)).

**Comment by zd9KgA** [comment]
Now, with the ability to run tests, I realized that my original analysis of the problem is wrong - in fact, I realized my understanding of rego is not sufficient to propose a fix. 

In summary, I can contribute only contribute the problem (i.e. test case which can be added to the set of tests in test_allow_group_policy), but not a fix.

**Comment by aeneasr** [comment]
Yes, that would be also helpful!

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
