### ISSUE TITLE
gRPC API 

### ISSUE THREAD

**Issue by nmarcetic** [ory/keto#136]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
I was thinking, how nice would be to see gRPC API, besides HTTP in order to improve performance, avoid serialization with protobuf and stay type-safe. I am concerned about performance issues and making a bottleneck in the system. There is a lot of benchmarks online which says that gRPC is 10x faster than HTTP JSON API doing the same thing. This gRPC API doesn't need to have everything that HTTP has, just 2-3 methods would be enough, even 1 method so I can [at least verify access by checking policy](https://www.ory.sh/docs/keto/sdk/api#check-if-a-request-is-allowed), this is most used API endpoint.

We are considering ory/Keto usage as [AuthZ server and ACL](https://github.com/mainflux/mainflux/issues/377) for [Mainflux IIoT platform](https://github.com/mainflux/mainflux). Our main goals are performance, scalability, and security, AuthZ and any kind of access control will have an impact on our performance (We are reaching hundreds of thousands msg/sec), but much less if we use gRPC API rather then HTTP.

I was wondering if gRPC API is something that yoiu would consider, at least for check access endpoint and do you see any drawbacks, blocks, etc...?

Thanks!

**Comment by aeneasr** [comment]
There are no plans for gRPC right now and as we'll have more unstructured input data in the future there will be a lot of designing neccessary to make it work and still get the benefits.

Having said that, I believe that going for gRPC right now is over-optimization as there will be a lot of other issues impacting performance more than JSON vs gRPC, so the incentive is quite low at the moment to have this on the road map, for us at least.

**Comment by nmarcetic** [comment]
Thanks, @aeneasr Closing this one.
