### ISSUE TITLE
Individual permissions can't be checked with REST API

### ISSUE THREAD

**Issue by kaiba42** [ory/keto#1418]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Ory Network Project

https://inspiring-lichterman-l25lz6u2q1.projects.oryapis.com

### Describe the bug

In Ory Permission Language, a user defines a namespace, and the `relations` (defined as `related`) and `permits` for objects within that namespace.

Keto has one REST API endpoint for checking the permissions of a subject: `relation-tuples/check`.
This endpoint takes 4 arguments (passed as either query params for GET requests, or in a JSON body for POST requests):
1. namespace
2. object
3. relation
4. subject_id

None of these arguments specify the _permission_ to be checked against the `permits` in a permissions model defined with Ory Permission Language. The caller is only able to check against the `relations` in a permissions model.

This seems like a fundamental issue, or there may be some alternative endpoint that checks against `permits` that I am unaware of.

### Reproducing the bug

None -- the bug is the absence of core functionality.

### Version

Ory Network

### On which operating system are you observing this issue?

None

### In which environment are you deploying?

Ory Network

**Comment by kaiba42** [comment]
I see that keys from both `permits` and `related` can be passed to the `relation` input.

**Comment by kaiba42** [comment]
There aren't any docs that tell you what can be passed into the relation input though. I feel like that's pretty key to using Ory Keto. The documentation for the relation argument is currently:
`relation | string | Relation to query`
This is not informative of usage.


mentation for the API is 
```

relation | stringRelation to query
-- | --




relation | stringRelation to query
-- | --

**Comment by elzbietaZ** [comment]
Totally agree, lost some time trying to understand exactly what you described.

**Comment by chrisgoddard** [comment]
+1 to this - it's very confusing
