### ISSUE TITLE
Cannot connect to MySQL

### ISSUE THREAD

**Issue by jboalml** [ory/keto#145]
**Describe the bug**

It is not possible to connect to MySQL using the DSN format.

**Reproducing the bug**

The issue is related to a change in Golang and was first reported here: https://github.com/golang-migrate/migrate/issues/264

**Expected behavior**

Keto should be able to connect to MySQL.

**Environment**

* Keto versions: Higher than v0.3.3 (it works in v0.3.3)
* Environment: Tested in Docker

**Additional context**

The issue has already been fixed: https://github.com/golang-migrate/migrate/pull/265
Most probably the solution is simply to update the Go version.

**Comment by aeneasr** [comment]
Thank you for the report - would you be up for version bump / PR? :)

**Comment by yuan1238y** [comment]
Hello @aeneasr .
This bug not repaired completely.
```
keto-migrate_1  | time="2020-03-05T09:28:49Z" level=fatal msg="Unable to parse configuration item \"dsn\", make sure it has the right format" dsn="mysql://root:eisoo.com@tcp(mysql:3306)/keto?max_conns=20&max_idle_conns=4" error="parse \"mysql://root:eisoo.com@tcp(mysql:3306)/keto?max_conns=20&max_idle_conns=4\": invalid port \":3306)\" after host"
```
The dependency library github.com/ory/x version is v0.0.93, currently latest version is v0.0.99, and fixed this bug `https://github.com/ory/x/commit/f09f5c955c86b9aa3eed222775da5020fbfce065`

**Comment by aeneasr** [comment]
Ah right, that still has to be fixed - would you be up for a PR? :)

**Comment by yuan1238y** [comment]
> Ah right, that still has to be fixed - would you be up for a PR? :)
😉
