### ISSUE TITLE
 msg=Unable to connect to database, retrying. audience=application error=map[message:unsupported dialect 'jdbc'] service_name=Ory Keto service_version=v0.11.1-alpha.0

### ISSUE THREAD

**Issue by nithinguruswamy** [ory/keto#1492]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

 msg=Unable to connect to database, retrying. audience=application error=map[message:unsupported dialect 'jdbc'] service_name=Ory Keto service_version=v0.11.1-alpha.0

I'm finding this error and unable to connect the db.

### Reproducing the bug

msg=Unable to connect to database, retrying. audience=application error=map[message:unsupported dialect 'jdbc'] service_name=Ory Keto service_version=v0.11.1-alpha.0

### Relevant log output

```shell
msg=Unable to connect to database, retrying. audience=application error=map[message:unsupported dialect 'jdbc'] service_name=Ory Keto service_version=v0.11.1-alpha.0
```

### Version

v0.11.1

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Kubernetes with Helm

**Comment by alnr** [comment]
Check the example docker-compose files for correct DSN strings:
https://github.com/ory/keto/blob/master/docker-compose-postgres.yml

**Comment by nithinguruswamy** [comment]
Thanks
