### ISSUE TITLE
warden: Check against multiple policies

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#15]
See https://github.com/ory/hydra/issues/264

**Comment by joshuarubin** [comment]
Is this just a placeholder, or is it planned to be developed soon?

**Comment by arekkas** [comment]
No, we're currently focusing on bringing the ecosystem to 1.0

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
