### ISSUE TITLE
Disable access logging or change level of logs for the health endpoints

### ISSUE THREAD

**Issue by moritzheiber** [ory/keto#150]
I would like to be able to disable access logging for the health endpoints, so that I can make sense of my application logs again. Inside Kubernetes, the health endpoints of Keto are checked regularly, with each checks equal to two lines in its logfile.

I would propose either of these two solutions:

1. Disable access logging for the health endpoints, akin to [what Hydra already has implemented](https://github.com/ory/hydra/blob/fb31d017fcec2ee52e94c0e1b88a66e58ccc893b/docs/config.yaml#L137-L139).
2. Shift the level of severity for the logs from `info` to `debug` to avoid logging them in a "production" context.

As an example, here are two lines in my logs that I encounter on a regular basis (i.e. every couple of seconds):

```
{"msg": "started handling request", "request": "/health/ready", "method": "GET", "level": "info", "time": "2020-01-22T11:51:21Z", "remote": "127.0.0.1:50224"}
{"msg": "completed handling request", "text_status": "OK", "request": "/health/alive", "took": 78385,  "measure#keto": {"latency": 78385}, "method": "GET", "level": "info", "time": "2020-01-22T11:52:42Z", "remote": "127.0.0.1:37770", "status": 200}
```
_Note: Not the same event._

Thanks!

**Comment by aeneasr** [comment]
Good idea, I think it would make sense to do what we've already done in ORY Oathkeeper:

https://github.com/ory/oathkeeper/blob/master/cmd/server/server.go#L82

What do you think? If you're up for it, we'd appreaciate a PR!

**Comment by moritzheiber** [comment]
See #151
