### ISSUE TITLE
Cannot run migrate command successfully in mysql

### ISSUE THREAD

**Issue by xiateapu** [ory/keto#177]
**Describe the bug**
Cannot run migrate cmd successfully in mysql

**Reproducing the bug**

1. Set mysql env
2. docker-compose up -d
3. docker logs -f 

*Server logs*
![image](https://user-images.githubusercontent.com/46192062/78674586-680ac880-7916-11ea-9758-d7a2a5f4bcea.png)

*Server configuration*
![image](https://user-images.githubusercontent.com/46192062/78674049-9936c900-7915-11ea-8968-15acccd38d42.png)

**Expected behavior**

Run migrate cmd successfully

**Environment**

* Version: v0.5.3-alpha.3
* Environment: Tested in Docker

**Additional context**

 The error log seems to express `db` variable has a `nil value` in `ory/keto/storage.(*SQLManager).CreateSchema`, I'm not sure if I did something wrong.

**Comment by aeneasr** [comment]
Sorry about that, patch and release are coming
