### ISSUE TITLE
When utilizing a cockroach DSN migration works, keto exits complaining about the driver for the DSN

### ISSUE THREAD

**Issue by sigil66** [ory/keto#196]
**Describe the bug**

Given the following DSN:

`dsn: cockroach://root@127.0.0.1:26257/keto?sslmode=disable`

keto sql migrate works, however when running `keto serve` keto exits with the following:

```
{"error":"no driver is capable of handling the given DSN","level":"fatal","msg":"Unable to instantiate service registry.","time":"2020-05-14T16:09:49-05:00"}
```
**Reproducing the bug**

Utilize a cockroach DSN with the config file, try running the migrations, try to start keto.

**Comment by aeneasr** [comment]
Yeah, Cockroach support has not been added to Keto yet!

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
