### ISSUE TITLE
IDs being limited to varchar(64) reduces the usefulness of URNs when you are using them globally

### ISSUE THREAD

**Issue by sigil66** [ory/keto#197]
**Is your feature request related to a problem? Please describe.**

IDs being limited to varchar(64) reduces the usefulness of URNs when you are using them globally

**Describe the solution you'd like**

I would like to be able utilize full blown URNs everywhere including keto Role and Policy IDs, this would greatly simplify the code I have to write to maintain state when URNs are referenced outside of keto.

**Describe alternatives you've considered**

Currently I use short IDs to represent policies and roles externally and expend them as a special case when viewed.

**Additional context**

**Comment by aeneasr** [comment]
Large varchar values have a high cost of indexing and some databases (e.g. MySQL) actually don't support long varchars for indexing (limit is 160 for some I believe) which is why this is set to 64!

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
