### ISSUE TITLE
Policy filters

### ISSUE THREAD

**Issue by sebastian-schlecht** [ory/keto#20]
Hey,

first of all thank you for this service, it seems awesome! Is there a way (planned) to filter policies, i.e. give me all the policies that match `some-scope:some-resource:<.*>`?

Thanks and cheers,
Sebastian

**Comment by arekkas** [comment]
Not right now, would be a smart addition though!

**Comment by sebastian-schlecht** [comment]
Alright, thanks!

**Comment by arekkas** [comment]
You can keep this issue open until it's resolved :)

**Comment by cobraz** [comment]
Hello there!

I'm working on a project where this is needed as well! :-)
Hola if you need help!

**Comment by aeneasr** [comment]
Any ideas how to implement that? :)

**Comment by sum2000** [comment]
@aeneasr this sounds similar to #121 , I can take it up once my PR #124 is approved. I am thinking to modify `ListOryAccessControlPolicies` to accept filters which will be `Subject`,` Resources`, `Actions`. Not sure if we want to add `Conditions` as well. On the `HTTP` side a query will look like `/engines/acp/ory/{flavor}/policies?subject=<some-subject>&resource=<some_resource>`. Although supporting advanced regex queries like `/engines/acp/ory/{flavor}/policies?subject=sum*&resource=<some_resource>` needs to be well thought out with possibly having a regex evaluator in storage. I am also a bit confused about the security aspect of it, how do we validate that requestor can get certain rows of the database or not.

**Comment by aeneasr** [comment]
I think filters could be implemented here. The problem of course is that we either do a string against regex match, or treat regex as strings. I'm not sure if the second is really all that useful?

> I am also a bit confused about the security aspect of it, how do we validate that requestor can get certain rows of the database or not? My guess is API consumers have to validate user on their end.

Good point, right now everyone would be allowed to read all policies. Maybe you could use Keto to limit that by itself (inception!) - but yeah would need some thinking ;)

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
