### ISSUE TITLE
Website menu hidden by ad

### ISSUE THREAD

**Issue by andrewbanchich** [ory/keto#209]
It's very hard to navigate the docs on mobile because the ads cover the nav menu.
 
![Screenshot_20200529-191043](https://user-images.githubusercontent.com/13824577/83312481-6a83f300-a1e0-11ea-9481-e06637a2aede.png)

**Comment by aeneasr** [comment]
Could you clarify what you mean with "nav menu"? I don't think we have a menu at the bottom of the page! Also, sorry for the inconvenience, but ads pay for hosting the docs :)

**Comment by andrewbanchich** [comment]
If you look at the bottom right, there is a small white box sticking up only a couple pixels above the ad. That's the nav menu for links that would normally appear in the right sidebar on desktop.

I realize ads help pay for things, but just letting you know you may want to fix it so that the menu is usable.

**Comment by aeneasr** [comment]
Ah I see! I didn't actually know that was there :)

**Comment by andrewbanchich** [comment]
Also, regarding hosting the docs, have you considered using a static site generator and GitHub Pages? That would be free.

**Comment by aeneasr** [comment]
We're using SSGs but do not host on GitHub Pages because they have had issues with build timeouts and silent deployment failures so we use netlify atm.

**Comment by andrewbanchich** [comment]
What about mirroring the repos and building with GitLab Pages / CI?

**Comment by aeneasr** [comment]
We're pretty happy with the current set up, it works very well. We have everything automated and with build pipelines and there is no manual intervention necessary - I don't think we'll make changes here any time soon as it's a ton of work to change the pipeline! Still, thank you for the ideas and input :)

**Comment by aeneasr** [comment]
The banner has since been removed!
