### ISSUE TITLE
Role setup not working

### ISSUE THREAD

**Issue by sebastian-schlecht** [ory/keto#21]
Hey,

I'm still experimenting with this service - I tried to setup roles.

My roles are:
`[
    {
        "id": "admin",
        "members": [
            "bob"
        ]
    }
]`

My policies are:
`[
    {
        "id": "f1d0ff27-5afd-49dd-9f58-9dffc0b99e35",
        "description": "",
        "subjects": [
            "admin"
        ],
        "effect": "allow",
        "resources": [
            "project:1:ticket:1"
        ],
        "actions": [
            "read"
        ],
        "conditions": {}
    }
]`

However, my request to `localhost:4466/warden/subjects/authorize` with the following content returns `{ "allowed": false }`.

Body:
`{
	"action": "read",
	"subject": "bob",
	"resource": "project:1:ticket:1"
}`

Am I doing anything wrong?

**Comment by arekkas** [comment]
No, it's a bug currently, see #19 - it will be fixed by tomorrow

**Comment by sebastian-schlecht** [comment]
Cool, thanks!

**Comment by arekkas** [comment]
You can keep this issue open until it's resolved :)

**Comment by sebastian-schlecht** [comment]
Thanks for fixing this! At which point are you updating the docker images? For every release?

**Comment by arekkas** [comment]
Once a new release is available, docker images are tested, built, and pushed to docker hub automatically

**Comment by abychkova** [comment]
The same situation with `localhost:4466/engines/acp/ory/exact/allowed` for Keto from full-stack example. Still reproduced.

**Comment by aeneasr** [comment]
The full-stack example is using an outdated version, most likely.
