### ISSUE TITLE
Wrong offset behavior when fetching roles with filter by member 

### ISSUE THREAD

**Issue by wizart** [ory/keto#216]
**Describe the bug**

The offset works wrong when use filtering by a member in fetch role collection endpoint.

---
The suggestion of cause: Filter applies after roles fetched from DB but offset and limit applied to the DB query without filtering by a member.

**Reproducing the bug**

1. add 2 roles and assign one member to second role.
2. `engines/acp/ory/glob/roles?limit=1&offset=0&member=<member id>` - response is null
3. `engines/acp/ory/glob/roles?limit=1&offset=1&member=<member id>` - response is second role

**Expected behavior**

On step 2 the result must be the second role. But received null

**Comment by aeneasr** [comment]
Nice find, are you open to fix this in a PR? :)

**Comment by wizart** [comment]
I would be happy to help, but Go is not my main language.
I still continue to develop the project with Keto, so when it will be on production I will need to fix it because it can cause users confusion :)
So in 1-2 months, I guess I will be able to help with it.
