### ISSUE TITLE
Config file not found because "Config File ".keto" Not Found in "[/]"

### ISSUE THREAD

**Issue by rafasad** [ory/keto#239]
I am following the documentation and I have this problem when I run any command through the docker.

```Config file not found because "Config File ".keto" Not Found in "[/]"```

**Example of commands**

```docker run --rm -it oryd/keto:v0.5.6-alpha.1 help```

```
docker run -it --rm \
  --network ketoguide \
  -e DSN=$DSN \
  oryd/keto:v0.5.6-alpha.1 \
  migrate sql -e 
```

<img width="932" alt="Screen Shot 2020-09-10 at 10 43 02" src="https://user-images.githubusercontent.com/8294278/92738706-8dcb4c00-f352-11ea-81b6-c9285495db76.png">

**Reproducing the bug**

_Steps to reproduce the behavior:_

Follow all steps in the Installation and Configure and Deploy section of the guides including Run the Ory Keto Service

_Expected behavior_

I expected that running and complete without error.

**Environment**

Version: v0.5.6-alpha.1

**Comment by aeneasr** [comment]
It's just a warning, you can ignore it.

**Comment by g13013** [comment]
@aeneasr this warning is also displayed when called from the CLI which is confusing because it's like an error

From the getting started guide:

![image](https://user-images.githubusercontent.com/2730430/103926672-84dc6280-5119-11eb-8402-6a4c254bdb72.png)
