### ISSUE TITLE
Rewrite check engine to search the graph in the other direction

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#302]
**Is your feature request related to a problem? Please describe.**

The paper states that the relation tuple table defines two indices, one on `object` and one on `object, relation` (<- user set).
The expand API requires lookup of user sets and the check API can either start searching from the object or from the subject. The index suggests that zanzibar searches starting from the object. This also makes sense in many settings because there will be statistically less relation tuples for one object than for one subject.

**Describe alternatives you've considered**

Making this configurable per namespace would also be possible. Are there any cases where there would be less relation tuples for one subject than object?

**Comment by robinbraemer** [comment]
The new flipped search path totally makes sense.
I guess this can be closed know.

**Comment by zepatrik** [comment]
Yes, unfortunately github does not automatically close issues if you don't merge the referring PR into the main branch.
