### ISSUE TITLE
How to authenticate and authorize requests for Keto API?

### ISSUE THREAD

**Issue by robinbraemer** [ory/keto#309]
**Is your feature request related to a problem? Please describe.**

How and what mechanisms do we support to authorize API requests.

One authorization we support is:

- mTLS, a certificate issued for the exact principal with its name on the common name (CN) field.
- either we make the admin CN configurable or we add a small user system to create keto API users

Please suggest more possible solutions to this kind of "chicken and egg" problem:

**Comment by zepatrik** [comment]
The way we usually solve this is that we partition the API in admin and public, so that both run on different ports. Then you can expose the admin internally, use mTLS for authentication, ... See https://github.com/ory/hydra/issues/1962 for how this should work in hydra.

**Comment by aeneasr** [comment]
Yes, ORY Keto should be agnostic to this. Some people want mTLS, others basic auth, others an api key, and so on. We have good solution to address this stuff (e.g. ORY Oathkeeper, ORY Hydra, ...) and could offer run-of-the-mill configs and env set ups for this. We've been quite strict when it comes to separation of concerns in this regard in other projects and I'd like to follow the other project's footsteps!

However, one thing to think about is obviously how we distinguish between the clients. Do we identify them using authentication? Or just using a path component in the REST or an argument in GRPC similar to namespace?

**Comment by zepatrik** [comment]
As clients and Keto will both be "internal", we could follow the Oauth2 approach where you get a secret and client ID when you create a new client. This can then be used like an API key.

**Comment by aeneasr** [comment]
In my opinion, I would try to avoid this as it leaves many questions open - how do we CRUD clients? Is the password hashed? If it is hashed, what algorithm do we use (remember low latency). Is a secret really enough or do we want TLS? I currently am trending towards `/clients/foo/namespaces/bar/relations` (assuming a namespace always has at least one client). This would allow one to add e.g. ORY Oathkeeper matching `/clients/<client_id>/namespaces/<namespace_id>/relations` and use this to check authorization after authentication (using e.g. basic auth, api key auth, mTLS, ...).
