### ISSUE TITLE
Logging of reponse context would be helpful

### ISSUE THREAD

**Issue by jdnurmi** [ory/keto#368]
When implementing keto, especially at early stages, and doubly so when doing with oathkeeper, it's sometimes helpful to know _what_ is being accepted/rejected.  Similarly when pulling an old audit trail, knowing that a request was properly limited/scoped when a decision was made is helpful.

Keto logging with at least the latest docker image doesn't give context on _what_  was allowed/denied, merely that it was.

Understandably, this could be a security concern if logs expose sensitive resource names, etc, but it would be nice to have that option;  Knowing that oathkeeper is sending what I expect it to helps me to move up the debugging chain;  Knowing that my app is sending the wrong thing helps me move down the debugging chain.

**Describe the solution you'd like**

An option to include in the logging for the `allowed` call details

`
log.allowed.show_{resource,action,subject,context} = true
`

would allow very granular control, and defaulting to false would allow people to opt-out of aggressive logging or overly sensitive logging. (Personally, I don't use sensitive ID's in resources/actions/subjects, but could see the desire to opt in granularly)

**Describe alternatives you've considered**

Crossing my eyes trying to distinguish `foo:bar:baz:buzz` and `foo:baz:bar:buzz` or `user:long-arse-guid` and `users:long-arse-guid` in oathkeeper configs or code, and not being sure if it's my fault or keto's fault (it's, almost always, mine)

**Comment by aeneasr** [comment]
Yes, this makes a lot of sense. Actually, I think we should add OpenTracing for this to make it much easier to understand what is happening. This will not land in the current version of ORY Keto though, as we have a feature freeze. But we will definitely add this for #267
