### ISSUE TITLE
Keto integration with Kratos and Oathkeeper

### ISSUE THREAD

**Issue by obabichev** [ory/keto#381]
**My case**

Hallo,

I'm trying to adopt ORY stack for my purposes and In general, I'm really happy with that,

I applied Krato and Oathkeeper to store users and authenticate them, and it works really like a charm,

But when I started to apply Keto for authorization I started to struggle because I don't see a clear way of how Keto should communicate with other parts of the system.

I think my case is quite common I have a service that provides some functionality for users. Users can register in the service (Kratos), get some roles (roles should be provided dynamically for each user), and depending on roles make some actions.

Architecture:
Web SPA (React) --> Oathkeeper --> API server
                                                        +-> Kratos

At the current moment, Oathkeeper decides which requests should go into the API server (and which of them require authentication) or into Kratos.

**The problem**

There is no clear understanding of how Keto should work in such a system. I expect I can create a configuration for Keto which will have a description of possible actions and roles. I expect that I should be able to get the information of which user have which roles and be able to add certain roles to certain users via API (actually I haven't found how to do that yet),

but it's totally unclear how oathkeeper can match the user's session and user's permissions to pass/not pass a request to the API, how oathkeeper can add the permissions information to the request to allow server know about user's permission's, how frontend can get user's permission to be able to show/hide certain functionality for him...

**Proposal**

Kratos has a nice example https://github.com/ory/kratos-selfservice-ui-node of how Kratos might be used, is it a good idea to have a similar example of how Keto might be used in common scenarios? Cause at the current moment I feel the lack of documentation.

I also understand that such an example may exist but I haven't found it yet, if so I also will be happy to know about it.

**Comment by zepatrik** [comment]
I have to admit that we are definitely lacking of such examples, but Keto gets more love now with the complete rewrite we are working on (see #266 and #267). Until that is done we don't have the time to add nice examples, but there will be some with the first release we do of the new system. But you can definitely integrate the current Keto with Oathkeeper, I think https://www.ory.sh/oathkeeper/docs/pipeline/authz#authorizer-keto_engine_acp_ory will help you to get started. Documentation on how to make Keto and Kratos play nicely together is unfortunately not around, but others are building similar architectures. I guess if you ask on slack or open a GitHub discussion here and in Kratos, someone will give you a hint on how they approached it.

**Comment by obabichev** [comment]
Thank you for the answer,

I understood how to connect Oathkeeper and Keto (thank you for the link to the documentation page), but looks like it's better to wait for the finish of rewriting, at the current moment event the script from https://www.ory.sh/keto/docs/configure-deploy doesn't work (at least for me). I got the error `Config file not found because "Config File ".keto" Not Found in "[/]""` (I even found the issues about that and fix in one of the previous versions, but it didn't help me),

Anyway, I think I will try to adopt any other authorization tool for now, and repeat to Keto a bit later. I like how Ory tools look in general and hope to use them in the future =)
