### ISSUE TITLE
Don't use unsigned integers in ProtoBuf API

### ISSUE THREAD

**Issue by robinbraemer** [ory/keto#393]
- https://github.com/ory/keto/blob/921c630d02789dba80ee3c72df0e8ffd232903b6/api/keto/acl/v1alpha1/read_service.proto#L64

In regards to **Kubernetes API Conventions**: https://github.com/kubernetes/community/blob/master/contributors/devel/sig-architecture/api-conventions.md#primitive-types

> Do not use unsigned integers, due to inconsistent support across languages and libraries. Just validate that the integer is non-negative if that's the case.

What do you think? I think we should trust their experience and apply it as well.

**Comment by zepatrik** [comment]
Hm right, unsigned ints are not available in every language. I guess the generated clients will do some validation but it is indeed easier to just allow signed types there.
