### ISSUE TITLE
Elixir SDK

### ISSUE THREAD

**Issue by lucasclerissepro** [ory/keto#418]
**Is your feature request related to a problem? Please describe.**

We are willing to use Keto but our whole backend is developed in Elixir.

**Describe the solution you'd like**

As mentioned in the documentation, we can open issues to request for specific SDKs. Would that be possible to generate the SDK for elixir ? 

**Describe alternatives you've considered**
Using the OpenAPI specs from Keto and generating our own or simply doing API calls.

**Comment by aeneasr** [comment]
Hi Lucas - you can find our generated code pipeline over at https://github.com/ory/sdk - we appreciate PRs for new programming languages and also use OpenAPIGenerator!

**Comment by yordis** [comment]
This is not hard to do using https://hex.pm/packages/tesla

@aeneasr would you mind supporting me with the codegen stuff?

**Comment by aeneasr** [comment]
Sure! Check out this pr ( https://github.com/ory/sdk/pull/50 ) to see how we did it for Dart.js!

**Comment by aeneasr** [comment]
Superseded upstream PR
