### ISSUE TITLE
Add health check and version endpoints to read/write REST (and gRPC?) API

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#422]
**Is your feature request related to a problem? Please describe.**

See title

**Comment by zepatrik** [comment]
REST health check is already there, for gRPC follow https://github.com/grpc/grpc/blob/master/doc/health-checking.md

**Comment by aeneasr** [comment]
Ah nice, I overlooked those, thanks!

**Comment by aeneasr** [comment]
Version endpoints are still missing
