### ISSUE TITLE
SQL: make strings variable length

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#430]
Currently the column definitions use an arbitrary fixed string length. Researching a bit revealed that there are basically no advantages with that with any of our supported database systems. We should just make those strings variable length to allow applications to use any format they like. Making clear that using huge strings and pointing to the databases' documentation should be enough IMO.

**Comment by aeneasr** [comment]
Arbitrary length strings are expensive to index. Usually you have to define a prefix length for the index which can lead to serious performance issues if the prefix length is too short. Making the length explicit is much better IMO.

**Comment by zepatrik** [comment]
So I tried finding some best practices that explain your argument, but could find none for any of our supported databases.
The most interesting findings where from crdb: https://www.cockroachlabs.com/docs/v20.2/schema-design-indexes#best-practices

> Note that queries can benefit from an index even if they only filter a prefix of its columns. For example, if you create an index of columns (A, B, C), queries filtering (A) or (A, B) can still use the index. However, queries that do not filter (A) will not benefit from the index. This feature also lets you avoid using single-column indexes. Instead, use the column as the first column in a multiple-column index, which is useful to more queries.

> Use a STORING clause to store columns of data that you want returned by common queries, but that you do not plan to use in query filters.

But that is not related to this issue, just a general FYI.

**Comment by aeneasr** [comment]
> Prefixes must be specified for BLOB and TEXT key parts. Additionally, BLOB and TEXT columns can be indexed only for InnoDB, MyISAM, and BLACKHOLE tables.

https://dev.mysql.com/doc/refman/8.0/en/create-index.html

Same applies to all other databases, otherwise each index would need to represent up to 4GB (or more) of binary data.

**Comment by zepatrik** [comment]
I am sorry to bother you but I could not find any documentation for postgres on this. I even tried to create an index on a `text` column and it worked without a problem:

```shell
$ docker run -e POSTGRES_PASSWORD=password -d postgres:13
$ docker exec -it cc9 psql -U postgres
psql (13.2 (Debian 13.2-1.pgdg100+1))
Type "help" for help.

postgres=# create table foo (str1 text);
CREATE TABLE
postgres=# create index on foo (str1);
CREATE INDEX
postgres=# insert into foo values ('asdf köawedjljkösd aldfhlui sdfjkhn ladsfha lasdkfjhasdkjfhalöu ajdswfhnalkh alwdsfuhalk asdfhö');
INSERT 0 1
```

With mysql, as expected, I do get an error:

```shell
$ docker run -e MYSQL_ROOT_PASSWORD=password -d mysql:8
$ docker exec -it -e MYSQL_PASSWORD=password 67f mysql -p
mysql> use mysql
mysql> create table foo (str1 text);
Query OK, 0 rows affected (0.08 sec)

mysql> create index foo_idx on foo (str1);
ERROR 1170 (42000): BLOB/TEXT column 'str1' used in key specification without a key length
```

The main reason behind this issue is that I do not want to enforce an arbitrary length if there is no reason for that. If you insert large blobs, you should expect your database performance to degrade, but as there is no value from which on problems start to occur, I would rather just not put a limit there and let users decide themselves what they want to put into the database.

**Comment by aeneasr** [comment]
https://dba.stackexchange.com/questions/69161/character-varying-index-overhead-length-limit

**Comment by aeneasr** [comment]
It's simply not a good idea to have arbitrary data length in a system that is supposed to be indexing (read AND write) things fast. The length needs to be fixed to something and if people want longer things they can use hashing if they want to!

**Comment by zepatrik** [comment]
Ok thanks for the links. So the current limit of 64 is arbitrary, but should be sufficient for all use cases. I could just not find any good documentation around this.

**Comment by aeneasr** [comment]
SHA512 produces, if encoded as hex, 128 digits and is 64byte long - so it would only be supported if used as binary format. SHA256 would work well with 64 varchar limit

**Comment by zepatrik** [comment]
So what limit should we use then? Hex is not very efficient in a varchar context I guess. A radix of 64 would be better suited, which is 32 chars for 512 bits (if my math is correct there).

**Comment by aeneasr** [comment]
> A radix of 64 would be better suited, which is 32 chars for 512 bits (if my math is correct there).

Not sure I follow. 512bit/8 = 64byte which means you can't compress this more unless you store more bits per byte

**Comment by zepatrik** [comment]
Right, had an error there. But chars != bytes anyways, you could use all of unicode to get it down to a view chars. Which then again could overflow the pages in postgres, as those are measured in bytes.

Anyways, what should the limit be?

**Comment by aeneasr** [comment]
iirc MySQL 5.6 has issues with varchar > 64 so I guess 64 it is? We can always increase the limit later, but it's difficult to decrease it. 64 would support hex-encoded SHA256
