### ISSUE TITLE
Non-nil return values despite errors

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#433]
**Describe the bug**

I found places where a function returns a value despite it ending up in an error. This is a no-go for idiomatic Go and needs to be resolved. There are only few exceptions where this behavior is actually desired - for example when we recover from an error and need the value.

**Reproducing the bug**

https://github.com/ory/keto/blob/zanzibar/internal/persistence/sql/relationtuples.go#L61

**Comment by zepatrik** [comment]
Could not find any occurrence anymore, searched with the pattern `return (?!nil).*, .*err`, which only found the following false positives:
![Screenshot from 2021-03-09 14-01-37](https://user-images.githubusercontent.com/5354445/110474505-0895d980-80e0-11eb-9372-315e4bab0ab2.png)
