### ISSUE TITLE
Don't use fmt.Sprintf to construct queries

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#434]
**Describe the bug**

See title. The only exception is using static table names (read: constant strings). **Never, ever do that for anything else.**

**Reproducing the bug**

https://github.com/ory/keto/blob/zanzibar/internal/persistence/sql/relationtuples.go#L109-L122

**Comment by zepatrik** [comment]
How else do you provide a dynamic `where` statement?

**Comment by aeneasr** [comment]
Find another way, use the pop query builder for example. [Don't ever use user input in sprintf for SQL statements](https://owasp.org/www-project-top-ten/2017/A1_2017-Injection).
