### ISSUE TITLE
Add golangci-lint with gosec linter

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#435]
**Describe the bug**

See title

**Reproducing the bug**

It should detect incorrectly created SQL statements using sprintf. Make sure that gosec actually runs and finds the current SQL statements in question.

**Comment by zepatrik** [comment]
Ensured gosec is running:
```
golangci-lint run
internal/driver/daemon.go:5:2: G501: Blocklisted import crypto/md5: weak cryptographic primitive (gosec)
        _ "crypto/md5"
        ^
```

Could not get it to report the `fmt.Sprintf` though... Are you sure that it detects pop as an SQL driver?

**Comment by zepatrik** [comment]
`gosec` is already included as I proved before. It seems to not detect pop as an SQL driver.
