### ISSUE TITLE
Allow deletion of relation tuples

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#452]
**Is your feature request related to a problem? Please describe.**

Currently, relation tuples can not be deleted. The gRPC interface already provides the necessary functionality.

**Describe the solution you'd like**

Delete relation tuples. REST endpoint should use the `DELETE` method.

The big question is how we identify them, because they are not unique #292. Delete all matching? Delete all up to a specific timestamp (=snaptoken/zookie)?

**Comment by aeneasr** [comment]
For now I would delete all matching ones!
