### ISSUE TITLE
Remove SQL logger

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#454]
**Describe the bug**

The SQL logger - enabled with log level trace - logs SQL statements and their values. This can lead to leakage of PII or other sensitive information to log files (see e.g. https://www.wired.com/story/facebook-passwords-plaintext-change-yours/) and should be removed.

**Comment by zepatrik** [comment]
Should we only log on `leak_sensitive_values` or remove that completely?

**Comment by aeneasr** [comment]
Remove completely, we have Jaeger for real tracing :)
