### ISSUE TITLE
Do not use latest tags in docker-compose examples

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#481]
See https://github.com/ory/keto/pull/266/files#diff-80581fdb34718578db1b0a0d81d5ed2ddf25c34515b74c690b22f533e9536fb5R5

We solve this in Ory Kratos:

- https://github.com/ory/kratos/blob/master/quickstart.yml#L5
- https://github.com/ory/kratos/blob/master/docs/config.js#L30-L35

**Comment by zepatrik** [comment]
Why not use `latest` and replace that? Seems a bit more clear to me than having random versions scattered in the docs. It would only be `latest` in the `/next` docs anyways.

**Comment by aeneasr** [comment]
Because people copy that and then complain why their system is buggy (e.g. one node has a different latest image than the other node) and we spend hours of time trying to understand what the fuck is going on. Instead we just say `don't use latest` and that often resolves the issue anyways.

**Comment by zepatrik** [comment]
Resolved with https://github.com/ory/keto/pull/266/commits/e45b28fec626db35f1bd4580e5b11c9c94a02669
