### ISSUE TITLE
SDK for .NET

### ISSUE THREAD

**Issue by biqas** [ory/keto#494]
**Is your feature request related to a problem? Please describe.**
The SDK for .NET is missing.

**Comment by zepatrik** [comment]
https://github.com/ory/sdk/tree/master/clients/keto/dotnet

**Comment by biqas** [comment]
@zepatrik I guess in the documentation the .NET SDK is not mentioned.

**Comment by zepatrik** [comment]
Right, can you maybe update the SDK pages @vinckr for all projects? Thanks for pointing that out @biqas
