### ISSUE TITLE
Cockroach specific persister

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#504]
**Is your feature request related to a problem? Please describe.**

It might be useful to have a cockroach optimized persister for truly distributed (multi-region/multi-cloud) settings. Only cockroach (from our currently supported databases) can be used in such a setup. We should investigate if we can leverage some features from it. As far as I can tell there is nothing comparable to spanners "true-time" at the moment.

## Features we can use and for what reason

- [Fine tune the cost optimizer to reduce latency](https://www.cockroachlabs.com/docs/stable/cost-based-optimizer.html)
- ...

**Comment by nathanclayton** [comment]
It looks like you support the general PostgreSQL protocol - if that's the case you could also look at YugabyteDB - it supports multiple region/cloud while being a more or less drop-in replacement for Postgres.

**Comment by zepatrik** [comment]
Sure, that can be used as well. Cockroach can also be used as a drop in replacement of postgres.
It is more about specific distributed features available on top of that like [follower reads](https://www.cockroachlabs.com/docs/stable/follower-reads.html) or the afore mentioned cost optimizer. A list of such yugabyte features might be helpful as well.

**Comment by jameshartig** [comment]
Yugabyte recently added follower reads as well: https://github.com/yugabyte/yugabyte-db/issues/5232. Not sure about the cost optmizer.

**Comment by robinbraemer** [comment]
I'm a database nerd and have used Yugabyte and Cockroach alot and read about benchmark comparisons and am not satified with Yugabyte from the deployment perspective (k8s) and [perfomance](https://www.cockroachlabs.com/blog/unpacking-competitive-benchmarks/) wise. Considering the goal for Keto to support "Google scale" Cockroach is a much more suitable database designed for global distribution developed by amazing engineers.

Nevertheless, it's PostgreSQL syntax at the end, which both databases support. I just want to make sure that everyone does its research and is not misslead by Yugabyte's marketing containing false assumptions manytimes and incomplete benchmarks.

**Comment by aeneasr** [comment]
Nice, thank you :) We also had our fair share of issues with CRDB and it's quite difficult to get answers from core engineering even as paying customers. For example, the current table-separated model does mot scale at all with CRDB as CRDB is optimized for few large tables instead of many small ones.
