### ISSUE TITLE
Require relations to be defined in the namespace config

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#509]
**Is your feature request related to a problem? Please describe.**

Currently the namespace config is useless. Later on we will define relations and their effect there: #303 

**Describe the solution you'd like**

For starters we should require relations to be defined in the namespace config. This will allow a seamless migration later on and prevents typos and other small errors.

This feature does not impact the current functionality.

**Comment by xbitres** [comment]
Isn't this needed in order to have inheritance between relations (example: owner is equivalent of read and write relations) or do you see it implemented in another way?

**Comment by zepatrik** [comment]
It is not strictly needed. See #877 for how we implemented that. This issue was rather about validation pre rewrites, so we can actually close this.

**Comment by xbitres** [comment]
Thank you for your answer. It would be cool that the documentation is updated with an example on how to use it, as it was tricky for me to find the issue

**Comment by zepatrik** [comment]
Yes, we will very soon update a lot of docs around namespace config, e.g. https://github.com/ory/docs/pull/948
Do you have any specific suggestions? What page were you struggling with?
