### ISSUE TITLE
ABAC with Groups and Sub Groups.

### ISSUE THREAD

**Issue by ovidius72** [ory/keto#51]
I need to implement an ABAC system with the following requirements:
- there will be groups
- groups can have subgroups and subgroups can have other subgtoups
- each group will have its own roles.
- a role called "Admin" can be in groups A and in Group B too, and they can have completely different permission (policies).
- An Admin of the Group A can be assigned/removed permissions to view all children groups or just a few of them.
- A role inside a group can be granted the permission to see resources of that group and  some resources of the children groups.

Following the keto tutorial I was able to set up the docker container and start adding roles and policies. However It seems that a role is just an id field. No additional information can be added. In such a case what is the best approach to assign roles to a group and how to create groups. I was looking for some field like context or attribute but there's nothing like that.

Is it possible to use keto for a system like the one I described above ?
Thanks.

**Comment by aeneasr** [comment]
ABAC itself might  be supported in the future (see #48 #47) regarding your concrete use case I can not dive into it too much as it seems to be very specific to your problem domain, but from a high level it looks like it should be solvable with the current policy model.
