### ISSUE TITLE
Resolve CI build issues when releasing Ory Keto

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#521]
https://app.circleci.com/pipelines/github/ory/keto/1018/workflows/0e435a2f-2196-49d1-97d4-a88a2ed96d22

- [x] https://app.circleci.com/pipelines/github/ory/keto/1018/workflows/0e435a2f-2196-49d1-97d4-a88a2ed96d22/jobs/7097
- [x] https://app.circleci.com/pipelines/github/ory/keto/1018/workflows/0e435a2f-2196-49d1-97d4-a88a2ed96d22/jobs/7095
- [x] https://app.circleci.com/pipelines/github/ory/keto/1018/workflows/0e435a2f-2196-49d1-97d4-a88a2ed96d22/jobs/7093

**Comment by zepatrik** [comment]
checked and all of these seem to be resolved already
