### ISSUE TITLE
proto: remove is_last_page field and use empty next_page_token instead

### ISSUE THREAD

**Issue by robinbraemer** [ory/keto#524]
I suggest that we stick to Google's API Improvement Proposals just as I had in mind when I designed the ACL API at the beginning.

Adding an additional field to the API shouldn't be done https://github.com/ory/keto/blob/a1d63b8f31fbd0f0e27248a5b9879e336684b002/proto/ory/keto/acl/v1alpha1/read_service.proto#L94
but instead reuse `next_page_token` and set it empty if there is no next page:
```protobuf
  // If this field is omitted, there are no subsequent pages.
  string next_page_token = 2;
```
and this should be the only way to communicate "end-of-collection" to users.

Please see https://google.aip.dev/158 for more details.

**Comment by zepatrik** [comment]
Relevant point:

> If the end of the collection has been reached, the next_page_token field must be empty. This is the only way to communicate "end-of-collection" to users.

The idea was to allow continuous pagination, where it is safe to provide any page token. We did not want to denote the first page **and** last page with an empty string.
But in the after sight I would say it makes no difference whether you check for an empty string or extra bool field, so let's follow the recommendation. What do you think @aeneasr ?

**Comment by aeneasr** [comment]
SGTM
