### ISSUE TITLE
Add examples for a typical web application

### ISSUE THREAD

**Issue by kenfdev** [ory/keto#546]
**Is your feature request related to a problem? Please describe.**

First of all, thanks for all the great work. I'm extremely excited about the keto/zanzibar and am willing to be able to contribute in the future. I've read the docs and have a question about the use case inside a typical web application. How and where to enforce the authorization. Apologies upfront if I'm totally missing the point about the responsibilities of ory/keto.

I know keto/zanzibar is in the early phase, but I thought this question would arise every now and then, hence decided to post for discussion.

Suppose there's a doctor-patient management system and there's a "Patients List" view in the web app like the one below.
<img src="https://user-images.githubusercontent.com/3941889/114305321-a7b05580-9b12-11eb-8311-56fb212e75ef.png" height="200px" />

The requirements are:
- Doctors can **view** patients whose doctor-in-charge is in the same department.
- Doctors can **edit** information about the patient if they are in charge of the patient.
- Doctors can **add** new patients to the patients' list.

Departments, Doctors and Patients are related like the following figure.
<img src="https://user-images.githubusercontent.com/3941889/114305422-20171680-9b13-11eb-8872-869838137994.png" height="200px" />

Therefore, in the "Patients List" figure, when the logged-in user is "Doctor A", he can:
- **View** Patient A, B, C because the doctor-in-charge of them belong to "Department A"
- **Edit** "Patient A" and "Patient B" because the logged-in user(Doctor A) is in charge of them
- **Add** a patient because the logged-in user is a doctor

I'm still new to the syntax of Zanzibar, but IIUC the relations tuple will be something like the following(using plain words for readability):

```
patients:patient-a#view@(departments:department-a#member)
patients:patient-b#view@(departments:department-a#member)
patients:patient-c#view@(departments:department-a#member)
patients:patient-d#view@(departments:department-b#member)

departments:department-a#member@doctor-a
departments:department-a#member@doctor-b
departments:department-b#member@doctor-c

patients:patient-a#owner@doctor-a
patients:patient-b#owner@doctor-b
patients:patient-c#owner@doctor-a
```

Provided these resources, my question is:

1. How would the data fetcher enforce the authorization and filter the patients to fetch? For example, if the app uses SQL the SQL may look like this:
```sql
select *
from patients p
  -- JOIN to find out the departments of the doctor-in-charge
  inner join doctors d on p.doctor_in_charge = d.id
  inner join doctors_departments dd on d.id = dd.doctor_id
    and dd.department_id = any(select department_id from doctors_departments where doctor_id = :loggedInDoctorId)

-- ^Returns Patient A, B, C (D gets filtered out)
```
I'm wondering how the practice would be to create the `JOIN` statements or `WHERE` statements to enforce the authorization. For example, would some kind of SQLBuilder parse the `departments:department-a#member` subject to the SQL statement?

2. How would the view (especially if this a Single Page Application) know when to render the `Edit` button? I've seen the [Introspection API in Chef Automate](https://github.com/chef/automate/tree/master/components/authz-service#introspection-how-to-query-permissions). Asking the API "What can I do?" to let the front-end know what the logged-in user is capable of. How would one ask ory/keto "What can I do?"

3. What would a relation tuple be like for "Doctors can **add** new patients to the patients' list."? I can understand the relation tuple for objects that have already been created. But how does it look like when the object is not yet created? Or do I add something like `patients:patients-list#add@(doctors:doctors#member)`?

**Describe the solution you'd like**

An example of a typical web application authorization in the docs involving both the front-end and back-end.

**Additional context**

Some additional information I've searched before that are related to Open Policy Agent:
- [Write Policy in OPA. Enforce Policy in SQL.](https://blog.openpolicyagent.org/write-policy-in-opa-enforce-policy-in-sql-d9d24db93bf4)
- [Authorization Service in Chef Automate](https://github.com/chef/automate/tree/master/components/authz-service#introspection-how-to-query-permissions)
  - [Open Policy Agent in Practice: From Angular to OPA in Chef Automate](https://www.youtube.com/watch?v=jrrW855xL3s)

**Comment by zepatrik** [comment]
Thanks a lot for this detailed example. First off, it is absolutely valid and Keto is capable of delivering what you need. You might have missed [this docs page](https://www.ory.sh/keto/docs/guides/simple-access-check-guide), it at least partially covers your example. The OPA SQL post is *very* interesting, and I will think about how we could add a similar feature to Keto. Offloading the last part of access check back into the database scales really well, as explained in the post.
It really helps to have many examples, and yours is not well covered by others we have right now, I will put it on our todo list :+1: 
Maybe you want to contribute to it as well if you figure out some parts?

So some hints and pointers:

Your relations look on-point, exactly what you described.

1. The back-end should use the [List API](https://www.ory.sh/keto/docs/guides/list-api-display-objects) to get a list of patients to display in the front-end. In this example, you would require two API calls: one to get the department, and a second one to get all patients of the department.
2. To then conditionally display the `Edit` button, you use the check API (i.e. asking "Is <doctor> the owner of <patient>?")
3. This depends a bit on your overall system. If there are not only doctors, you probably want to add an RBAC part (a guide for that is also still on the list). Then you check if the current user is a doctor in your back-end "add patient" handler (or use a reverse proxy; guide also pending :sweat_smile:). You can also go a step further and add e.g. an "action" namespace that contains all kinds of actions, like "add patient". Then you add a relation tuple similar to `actions:add-patient#exec@(groups:doctors#member)`. The check API can then be used to ask "Is <user-id> allowed to exec <action-id>?"
But again, this depends on what else your application is capable of and how you want to handle it.

**Comment by kenfdev** [comment]
Thanks for the response!

> 1. The back-end should use the List API to get a list of patients to display in the front-end. In this example, you would require two API calls: one to get the department, and a second one to get all patients of the department.

One concern I had was, what if the department contained millions of patients? And if the view only required 10 patients since it would paginate. Is this where [Pagination](https://www.ory.sh/keto/docs/guides/list-api-display-objects/#pagination) comes into action(currently it doesn't have ordering options)?

In addition, when querying the data using SQL, will it be something like this (rather than manipulating a JOIN statement)?

```sql
select *
from patients p
where p.id = any(:viewablePatientIds)

-- where :viewablePatientIds is retrieved by the List API
```

> 2. To then conditionally display the Edit button, you use the check API (i.e. asking "Is the owner of ?")

I'm assuming the back-end asks for this and merges the information to the returning JSON like the following:

```json
{
  "id": "some-id",
  "name": "Patient A",
  "doctor_in_charge": "Doctor A",
  "can_edit": true <-- this part
}
```

> 3. This depends...

Got it ;) the "action" namespace seems like a great example. I think I got the point! I'll try thinking further about this.

> Maybe you want to contribute to it as well if you figure out some parts?

Yes, definitely ;) I'll need to have a better understanding though 😅

**Comment by zepatrik** [comment]
> One concern I had was, what if the department contained millions of patients?

Exactly, that is solved by pagination. I know that currently there is no way to sort it, and it is valid to require that. This really needs some new ideas, as Keto might not have the information you want to use for sorting. If you have any ideas, feel free to open a discussion around that.

> I'm assuming the back-end asks for this and merges the information to the returning JSON like the following:

That is a good solution, you could on the other hand also expose the check endpoint and then use it in the front-end. The back-end will of course also have to check if the action is allowed once you submit the update. So again, it depends on how you prefer to do it :wink: 

 > I'll need to have a better understanding though

Feel free to also ask questions in the [slack](https://slack.ory.sh/) if you have some smaller issues.

**Comment by kenfdev** [comment]
> Keto might not have the information you want to use for sorting

This seems difficult since the order attributes may change from time to time 🤔 Which leads me to the partial query approach and let the web application decide about the filtering and sorting.

Just an imagination but the request to something like the List API would be "What patients can Doctor A view?" and the response would be "Patients of doctors who belong to Department A". And with this response from keto/zanzibar, the data accessor in the web application will parse it to the following SQL.

```sql
select *
from patients p
  -- JOIN to find out the departments of the doctor-in-charge
  inner join doctors d on p.doctor_in_charge = d.id
  inner join doctors_departments dd on d.id = dd.doctor_id
    and dd.department_id = "department-a"
```

This is what I can think of atm. Will have to use Keto more to talk more specifically.

Another reference, what I was trying to talk about above, is related to the ARQ Request / Response in the following SO answer.

https://stackoverflow.com/questions/50707394/xacml-3-0-and-multiple-resources/50728708#50728708

> you could on the other hand also expose the check endpoint and then use it in the front-end

Exactly! That sounds similar to the Introspection API I mentioned above 👍
