### ISSUE TITLE
@ory/keto-grpc-client is missing from npm

### ISSUE THREAD

**Issue by tscpp** [ory/keto#547]
**Describe the bug**

In https://www.ory.sh/keto/docs/sdk/index NodeJS gRPC (with TypeScript) https://www.npmjs.com/package/@oryd/keto-grpc-client is missing from NPM or it is a private package.

**Reproducing the bug**

1. Log out of NPM
2. Go to https://www.npmjs.com/package/@oryd/keto-grpc-client
2. Go to https://www.npmjs.com/package/@ory/keto-grpc-client
3. Notice the not found page on both urls.

**Expected behavior**

Please, publish the package as alpha in NPM.

**Environment**

- Version: v0.6
- Environment: 

**Additional context**

**Comment by zepatrik** [comment]
https://www.npmjs.com/package/@ory/keto-grpc-client

finally...
