### ISSUE TITLE
Example against best practices

### ISSUE THREAD

**Issue by pommelinho** [ory/keto#561]
**Describe the bug**

IN https://www.ory.sh/keto/docs/concepts/namespaces it's stated  in the example:

```
// relation describes a relation of the object towards the subject
directories:803a87e9-0da0-486e-bc08-ef559dd8e034#parent@(files:11488ab9-4ede-479f-add4-f1379da4ae43#_)
```

However in  https://www.ory.sh/keto/docs/concepts/graph-of-relations in the example you are doing exactly this bad practice:

```
// Have a look on the subjects concept page if you don't know the empty relation.
dir1#parent@(file1#)
```

should be rather

`dir1#child@(file1#)`

**Comment by zepatrik** [comment]
Thanks, the examples on that page indeed need some reworking.
