### ISSUE TITLE
engine: Implement AWS IAM Policies

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#59]
Press 👍 if you want to see this in ORY Keto and 👎 if not!

**Comment by sevenlure** [comment]
👍TOP TOP 👍

**Comment by harwee** [comment]
Any updates on this?

**Comment by aeneasr** [comment]
I am closing this issue as our Google Zanzibar-based refactoring is scheduled to be released soon. Ory Keto up to version 0.5 will go in hibernation mode and receive only critical security patches.
