### ISSUE TITLE
Distributed tracing is missing datadog support

### ISSUE THREAD

**Issue by christian-roggia** [ory/keto#593]
The rest of the ory stack is currently supporting datadog as distributed tracing provider while Keto doesn't.

**Comment by aeneasr** [comment]
I believe tracing is merged on master @zepatrik ?

**Comment by zepatrik** [comment]
We have the standard Ory tracing capabilities since #536. Can you pin-point the difference between Keto and some other project you are referring to @christian-roggia ?

**Comment by christian-roggia** [comment]
Ory keto currently supports only jaeger tracing:
https://www.ory.sh/keto/docs/reference/configuration/

Other ory products support also datadog, zipkin and other tracing platforms:
https://www.ory.sh/hydra/docs/reference/configuration/

**Comment by zepatrik** [comment]
I see, that actually is just a docs/config schema issue then. The code is capable of any of those but we forgot to add it to the config schema.
