### ISSUE TITLE
Bulk deletion of relation tuples

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#599]
**Is your feature request related to a problem? Please describe.**

To allow full RBAC #598, we have to delete multiple (might be thousands) relation tuples at once. Another use case is where a user has to be fully deleted (think GDPR and friends) or general cleanup tasks. Keeping relation tuples for deleted objects/users might not be desirable or even a bug if another object is created with the same identifier at some later point.

**Describe the solution you'd like**

Allow specifying partial relation tuples similar to the list API for deletion.

**Describe alternatives you've considered**

Keep current behavior and require clients to iterate over all relation tuples and deleting them.

**Comment by vancanhuit** [comment]
Hey, I can take this issue.

**Comment by zepatrik** [comment]
Good, the idea is basically to allow supplying partial tuples just like the list API. Maybe you can even reuse it's SDK definitions.
