### ISSUE TITLE
Cannot use @ory/keto-grpc-client in js due to error

### ISSUE THREAD

**Issue by DZhuribeda** [ory/keto#606]
**Describe the bug**
I tried to use js client for keto and it's failed during import.

```
Uncaught:
Error: Cannot find module '../../../../ory/keto/acl/v1alpha1/write_service_pb.js'
Require stack:
- <redacted>/node_modules/@ory/keto-grpc-client/write_service_grpc_pb.js
```

**Reproducing the bug**

1. Run `node`
2. Type `require('@ory/keto-grpc-client/write_service_grpc_pb.js')`
3. You will see an error 

**Expected behavior**

**Environment**
- Node.js v15.0.1.

**Additional context**

**Comment by zepatrik** [comment]
Ok I looked a bit into this. I think we have to make the whole `proto` directory the npm module, as I could not see a way to set the import root.
The idea behind the current way was that we want to make it easier for importing, and not having as long paths. As a compromise I propose to have a main entry point file pointing to the latest API version. Making the imports more convenient will need some other mechanism.
This also does make sense IMO once we have multiple API versions as you can then either use latest (i.e. what version you have in `package.json`) or a specific older one even in parallel.
This might actually be the same for go generated code. WDYT @aeneasr?
