### ISSUE TITLE
Consul as an alternative persistant data store to SQL

### ISSUE THREAD

**Issue by heyakyra** [ory/keto#617]
**Is your feature request related to a problem? Please describe.**

For deployments which rely on distributed data storage ("high availability" in the sense that if one node goes down, the data is still available), it would be very useful to adopt Consul as an alternative storage backend to a SQL database.

**Describe the solution you'd like**

Presumably this would be a huge undertaking, but hopefully has some long-long term feasability?

**Describe alternatives you've considered**

There are high-availability SQL setups, but they're cumbersome. 

**Additional context**

Fin.

**Comment by aeneasr** [comment]
Hello @heyakyra - the Zanzibar whitepaper runs on top of [Google Cloud Spanner](https://cloud.google.com/spanner). Open-source alternatives to GCS are CockroachDB, YugaByte and some others whose names I forgot :D

Adopting Consul or other non-consistent datastores will be quite difficult (up to impossible) if we want to meet requirements laid out in Google Zanzibar. Therefore we have no plans to implement a K/V backend like Redis, Consul, ...

Also keep in mind that Consul is a service for service discovery and configuration, and is not marketed as a database. As such it might be not possible to run large datasets with many writes on Consul.

**Comment by heyakyra** [comment]
I see, thanks for the explanation. I'll close this ticket then!
