### ISSUE TITLE
Cannot configure Jaeger with a local_agent_address URI and configuration references Hydra

### ISSUE THREAD

**Issue by relvacode** [ory/keto#662]
**Describe the bug**

 Configuration of Jaeger tracing is inconsistent and broken.

  - Tracing configuration references Hydra instead of Keto https://www.ory.sh/keto/docs/next/reference/configuration
  - The example tracing compose file https://github.com/ory/keto/blob/master/docker-compose-tracing.yml uses `TRACING_PROVIDER_JAEGER_*` instead of `TRACING_PROVIDERS_JAEGER_*` as referenced in the configuration

    - Using `TRACING_PROVIDER_JAEGER_*` does not seem to have any effect

  - Using `TRACING_PROVIDERS_JAEGER_LOCAL_AGENT_ADDRESS=jaeger:6831` throws an error on initialisation due to a regex validation failure. 
```
keto_1              | tracing.providers.jaeger.local_agent_address: jaeger:6831
keto_1              |                                               ^-- does not match pattern "^\\[(([0-9a-fA-F]{1,4}:){7}[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,7}:|([0-9a-fA-F]{1,4}:){1,6}:[0-9a-fA-F]{1,4}|([0-9a-fA-F]{1,4}:){1,5}(:[0-9a-fA-F]{1,4}){1,2}|([0-9a-fA-F]{1,4}:){1,4}(:[0-9a-fA-F]{1,4}){1,3}|([0-9a-fA-F]{1,4}:){1,3}(:[0-9a-fA-F]{1,4}){1,4}|([0-9a-fA-F]{1,4}:){1,2}(:[0-9a-fA-F]{1,4}){1,5}|[0-9a-fA-F]{1,4}:((:[0-9a-fA-F]{1,4}){1,6})|:((:[0-9a-fA-F]{1,4}){1,7}|:)|fe80:(:[0-9a-fA-F]{0,4}){0,4}%[0-9a-zA-Z]{1,}|::(ffff(:0{1,4}){0,1}:){0,1}((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])|([0-9a-fA-F]{1,4}:){1,4}:((25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9])\\.){3,3}(25[0-5]|(2[0-4]|1{0,1}[0-9]){0,1}[0-9]))]:([0-9]*)$"
keto_1              |
keto_1              | The configuration contains values or keys which are invalid:
keto_1              | tracing.providers.jaeger.local_agent_address: jaeger:6831
keto_1              |                                               ^-- does not match pattern "^([0-9]{1,3}\\.){3}[0-9]{1,3}:([0-9]*)$"
```

**Reproducing the bug**

  - Run the example docker-compose-tracing file
    - It works, because the tracing configuration is ignored
  - Set the environment variables correctly
    - Now it doesn't work as the Jaeger local agent address is invalid

**Expected behavior**

Keto to start

**Environment**

- Version: v0.6.0-alpha.3
- Environment: Docker

**Additional context**

Hydra has an additional validator of `uri` for local_agent_address https://github.com/ory/hydra/blob/master/spec/config.json#L967 which would likely fix this

**Comment by zepatrik** [comment]
I see, your proposed fix looks good :+1: 
Would you be up for a PR?
@aeneasr what do you think about a schema repo that collects all of those cross-project schema parts so we don't have issues like that? It could expose the schemas as `embed.FS` so we just have to load them before compiling? Would then also be versioned using go modules so it will be easy to manage.
