### ISSUE TITLE
Cannot create multiple namespaces using "file:///" source

### ISSUE THREAD

**Issue by cvolante54** [ory/keto#669]
**Describe the bug**

When using a file as the source to configure the namespaces, the interface is limited to only one file, and the file itself is limited to only allow for one namespace to be created (source code: https://github.com/ory/keto/blob/master/internal/driver/config/namespace_watcher.go#L152)

**Reproducing the bug**

1. Run keto version v0.6
2. Configure the namespaces parameter in the configuration file to be "namespaces: file:///etc/extra/config/keto_namespaces.json"
3. Inside the keto_namespaces.json only one namespace definition is allowed (ex. { "id": 0, "name": "sample" })

_Server logs_
When an array of namespaces is passed into the file: 
```
level=error msg=could not parse namespace file audience=application error=map[message:json: cannot unmarshal array into Go value of type namespace.Namespace] file_name=/etc/extra/config/keto_namespaces.json service_name=ORY Keto service_version=master
```

_Server configuration_
The only relevant section:

```yaml
namespaces: file:///etc/extra/config/keto_namespaces.json
```

**Expected behavior**

I expect that multiple namespaces can be passed through a file namespaces source just like multiple namespaces can be defined in the configuration file itself.

**Environment**

- Version: v0.6
- Environment: Docker/Kubernetes

**Comment by zepatrik** [comment]
To specify multiple files, use an array of paths:
```yaml
namespaces:
  - file:///path1
  - file:///path2
  - file:///path3
```
or alternatively, point the path to the directory that contains all namespace files:
```yaml
namespaces: file:///keto-namespaces
```

**Comment by zepatrik** [comment]
The relevant code for that is here: https://github.com/ory/keto/blob/f53d3eb70b3e18f0d6ccc8c7cc399f366f5c79b9/internal/driver/config/namespace_watcher.go#L60-L69

**Comment by zepatrik** [comment]
@cvolante54 can you confirm this is working now?

**Comment by cvolante54** [comment]
@zepatrik Yes, using a directory path and multiple files worked!

**Comment by zepatrik** [comment]
Awesome :+1:
