### ISSUE TITLE
Add `max-depth` to Check API

### ISSUE THREAD

**Issue by danthegoodman1** [ory/keto#702]
**Is your feature request related to a problem? Please describe.**

It would be nice to have a `max-depth` parameter to the check API so checks could not go past a specific depth (and might fail as a result)

**Describe the solution you'd like**

Adding `max-depth` as a parameter

**Describe alternatives you've considered**

Expanding instead of checking... bad solution

**Additional context**

In the case of checks in a multi-tenant environment it would be great to prevent highly nested checks.

**Comment by danthegoodman1** [comment]
in a multi-tenant env. one would need some sort of check proxy to enforce the checks, which maybe indicates https://github.com/ory/keto/issues/703 is a better solution, but with this issue solved one could do a check proxy that enforces some max anyway

**Comment by zepatrik** [comment]
I think it also makes sense to apply `max-depth` to check :+1: Also with a config option for a limit.

**Comment by vancanhuit** [comment]
Is this issue still relevant? I would like to work on it.

**Comment by doodlesbykumbi** [comment]
@vancanhuit I have a draft PR for this

**Comment by doodlesbykumbi** [comment]
I have 2 approaches in mind in terms of the response that the user gets when maxDepth is hit. Note that in my suggested implementation the condition is met when maxDepth is encountered (not maxDepth+1), that means the condition is met if  `maxDepth=3` and the path to a relation has 3 steps... each step being a recursive call to `checkOneIndirectionFurther` after the first one.

1. At present, the [draft PR](https://github.com/ory/keto/pull/791) results in an error at maxDepth. This seemed reasonable at first but perhaps not now. 
2. After some thought it seems more reasonable for the semantics of the check API to be -> search for a path to relation up to the maxDepth, if none is found then return false.

Thoughts on the 2 approaches ?

**Comment by vancanhuit** [comment]
Great @doodlesbykumbi! Then I can learn from your PR.
Should we give `max-depth` a sensible default value, e.g. `5`?

**Comment by doodlesbykumbi** [comment]
@vancanhuit For sure! I'm actually not sure what is sensible in this case. Do you happen to have justification for `5`? 

I currently have 10 as the global default, and 0 as check default. Which means 10 is the effective default.

**Comment by vancanhuit** [comment]
@doodlesbykumbi I see in this [doc](https://www.ory.sh/keto/docs/guides/access-control-list-design-best-practices#:~:text=Avoid%20too%20deeply%20nested%20subject%20set%20indirections%20(more%20than%20~5).) so I suggested `5` as default value. Not sure if it is practical but I think `10` is also fine.

**Comment by doodlesbykumbi** [comment]
Thanks @vancanhuit. I updated the default to 5
