### ISSUE TITLE
Add `max-depth` to global config

### ISSUE THREAD

**Issue by danthegoodman1** [ory/keto#703]
**Is your feature request related to a problem? Please describe.**

It would be nice for multi-tenant environmentss to be able to specify a global `max-depth` such that requests would not be able to cause high latency and demanding DB queries.

**Describe the solution you'd like**

Adding `max-depth` as a something the `max-depth` query param cannot exceed.

**Describe alternatives you've considered**

None

**Additional context**

**Comment by zepatrik** [comment]
Makes sense :+1:

**Comment by doodlesbykumbi** [comment]
Trying to confirm I understand what is meant by
> `max-depth` to global config

Does this mean setting max-depth in the configuration passed to `serve`, such that the **effective** max-depth for any given request is the lesser one between the **global** max-depth vs the **request** max-depth ?

**Comment by danthegoodman1** [comment]
> Trying to confirm I understand what is meant by
> 
> > `max-depth` to global config
> 
> Does this mean setting max-depth in the configuration passed to `serve`, such that the **effective** max-depth for any given request is the lesser one between the **global** max-depth vs the **request** max-depth ?

@doodlesbykumbi yep!

**Comment by doodlesbykumbi** [comment]
Thanks @danthegoodman1. I follow the gist of this feature request and the motivation. I think the implementation should be straightforward. I wonder though if the idea of "depth" will be semantically consistent across **all the things** that will make use of this global value. It definitely is consistent between check and expand, just not sure if that will generally be the case.

**Comment by doodlesbykumbi** [comment]
So here's my proposal for an implementation

1. Add a `serve.read.max-depth` key to the config schema. Something like:
```
{
  "max-depth": {
    "type": "integer",
    "default": 1000,
    "title": "Maximum depth",
    "description": "The maximum depth on all read operations.",
    "minimum": 0,
    "maximum": 65535
  }
}
```
2. Consume that in the Config provider
```
