### ISSUE TITLE
DELETE member from role 

### ISSUE THREAD

**Issue by SterlingAr** [ory/keto#74]
**Describe the bug**
When I try to delete a member from a role, it returns Method Not Allowed. 

**Expected behavior**
The members should be deleted succesfully.

**Version:**
 - Environment: Docker
 - Version:  v0.2.2-sandbox_oryOS.10: 

**Additional context**
In the [configure & deploy](https://www.ory.sh/docs/next/keto/configure-deploy) section the docker image used is oryd/keto:v0.2.2_oryOS.10, I tried fetching this image, In case this one allows me to delete roles,  but I get a manifest error: 

```
$ docker run oryd/keto:v0.2.2_oryOS.10
Unable to find image 'oryd/keto:v0.2.2_oryOS.10' locally
docker: Error response from daemon: manifest for oryd/keto:v0.2.2_oryOS.10 not found````

**Comment by aeneasr** [comment]
Yeah, that should be `docker pull oryd/keto:v0.2.2-sandbox_oryOS.10`. Would you mind creating a PR against [this file](https://github.com/ory/docs/edit/master/docs/keto/configure-deploy.md) to fix this?

**Comment by aeneasr** [comment]
closed by https://github.com/ory/docs/pull/101

**Comment by SterlingAr** [comment]
I'm still left with the issue of not being able to remove a member from a role.

**Comment by SterlingAr** [comment]
Any updates on this issue?

**Comment by aeneasr** [comment]
No, but feel free to pull up a PR!

**Comment by SterlingAr** [comment]
I've dug around the code and found this: 

`r.DELETE(BasePath+"/roles/:id/members/:member", e.sh.Upsert(e.rolesMembersRemove))`

To delete a member you actually have to include the member in the path, like this: 
`/engines/acp/ory/regex/roles/super-admin/members/bob`


The [docs](/engines/acp/ory/regex/roles/super-admin/members/bob) mention something different. 

I've tested this with version **v0.2.3-sandbox_oryOS.10**

**Comment by aeneasr** [comment]
Right! Seems like a copy & paste error - would you be open to fixing that in a PR? :)

**Comment by SterlingAr** [comment]
I would, however I don't know **go**.  Btw, do you mean it is an error within the swagger annotation or the code itself?

**Comment by aeneasr** [comment]
It's only a documentation issue, sorry for the late response by the way.
