### ISSUE TITLE
Support for nginx http_auth_request_module

### ISSUE THREAD

**Issue by kewde** [ory/keto#75]
**Describe the solution you'd like**
https://docs.nginx.com/nginx/admin-guide/security-controls/configuring-subrequest-authentication/
nginx can authenticate each request to your website with an external server or service. To perform authentication, NGINX makes an HTTP subrequest to an external server where the subrequest is verified. If the subrequest returns a 2xx response code, the access is allowed, if it returns 401 or 403, the access is denied. Such type of authentication allows implementing various authentication schemes, such as multifactor authentication, or allows implementing LDAP or OAuth authentication.

**Comment by aeneasr** [comment]
Yes, 403 indicates valid authentication credentials but insufficient access rights. This is exactly the case here - Keto does not check authentication credentials for validity.

**Comment by pecigonzalo** [comment]
This is more in scope of oathkeeper right? I felt it was worth commenting here as there was a similar ticket in this project.
