### ISSUE TITLE
HTTP API Documentation with weird layout

### ISSUE THREAD

**Issue by fakegermano** [ory/keto#752]
**Describe the bug**

When accessing the HTTP API docs via [this link](https://www.ory.sh/keto/docs/reference/rest-api) the layout is kind of broken, wiith an empty column to the right on medium to large displays.

![Screen Shot 2021-10-04 at 15 33 11](https://user-images.githubusercontent.com/5588341/135905419-fbb565ae-2816-49cb-95c3-4da91458985d.png)

![Screen Shot 2021-10-04 at 15 33 25](https://user-images.githubusercontent.com/5588341/135905439-d4ee8626-e47f-479f-81c9-bbfdf86d9dad.png)

**Reproducing the bug**

1. Access website https://www.ory.sh/keto/docs/reference/rest-api
2. If needed, change display size from browser developer tools
3. Check that the layout at the right is weird.

**Expected behavior**

It is expected that the website fills the entire screen with relevant content. 

**Environment**

- Checked in:
  - Firefox
  - Chrome

**Additional context**

Appears on dark and light mode

**Comment by zepatrik** [comment]
Right, this seems to be a problem in the Keto docs but not the Kratos docs... investigating

**Comment by aeneasr** [comment]
@zepatrik I wrote this and will take it on

**Comment by zepatrik** [comment]
fixed already :wink:

**Comment by aeneasr** [comment]
:D
