### ISSUE TITLE
List API: namespace should not be required anymore

### ISSUE THREAD

**Issue by zepatrik** [ory/keto#761]
**Describe the bug**

The namespace parameter is marked as required in the API spec. Also, we need a test to ensure that queries across namespaces actually work.

**Expected behavior**

Make the namespace parameter not required anymore. Make sure that all docs are updated accordingly.

**Comment by Lakshay-Pruthi** [comment]
Hey I'm a beginner and I would like to work on this issue.

**Comment by dhiemaz** [comment]
Is this issue still open?

**Comment by zepatrik** [comment]
Yes

**Comment by mnc-roov** [comment]
Okay, I want to help with this issue if it is still open.

**Comment by dhiemaz** [comment]
Okay, I want to help with this issue if it is still open.

**Comment by vancanhuit** [comment]
Is there anyone working on this issue?

**Comment by dhiemaz** [comment]
@vancanhuit it is still open, if you are willing to help with this then the floor is yours..

**Comment by vancanhuit** [comment]
Okay. I can take this issue. 🙂
