### ISSUE TITLE
cats video example broken in v0.7.0-alpha.0 

### ISSUE THREAD

**Issue by Uli-Tiger** [ory/keto#763]
**Describe the bug**

When following the guide https://www.ory.sh/keto/docs/next/quickstart you clone the latest and greatest :-) keto, so basically  v0.7.0-alpha.0 . When starting the cats example via docker compose you get the following init output.
```
NAMESPACE OBJECT RELATION NAME SUBJECT
videos /cats/1.mp4 owner
videos /cats/1.mp4 view
videos /cats/1.mp4 view
videos /cats/2.mp4 owner
videos /cats/2.mp4 view
videos /cats owner
videos /cats view
```
So all tuples are created with empty subject, which is already contra-dictionary to the example output given in the guide. Anyways when you follow the guide the application continuous to behave differently.
For example `keto check "*" view videos /cats/1.mp4` should return ALLOWED, but instead it returns DENIED. Considering the fact that subjects were initialized withe empty values, this somewhat expected.

**Reproducing the bug**
- follow the quick start guide: https://www.ory.sh/keto/docs/next/quickstart

**Potential fix**
i could fix this locally, by upgrading the keto version in
contrib/cat-videos-example/cats-exmapleketo.yml
contrib/cat-videos-example/docker-compose.yml
to v0.7.0-alpha.0

**Comment by zepatrik** [comment]
The relation tuple files were updated accordingly, but the image versions in the `docker-compose.yml` were not, sorry for that.
Don't we have automation for that already @aeneasr? Otherwise it would be a good use of the pre-release hooks :wink:

**Comment by zepatrik** [comment]
But this is not part of the docs, but the `docker-compose.yml` for the quickstart.
