### ISSUE TITLE
ListIdentities Pagination Starts at 1 instead of 0

### ISSUE THREAD

**Issue by hungcs** [ory/keto#797]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

- `ListIdentities` pagination starts at index 1 instead of index 0. Page 0 is the same as page 1.
- `ListIdentities` output gets truncated - there's some weird behavior when removing roles for one user, a role would suddenly pop up for another user, which makes me believe that there’s some maximum constraint. I don’t think we’re really returning that much data though, only around 30 users and 3-4 roles per user. This behavior became normal after we removed a lot of role assignments

### Reproducing the bug

https://user-images.githubusercontent.com/85463385/146244909-c4cac2e3-d417-4760-bfe9-5bfbc0ca1037.mov

Conversation with Patrik:
- https://ory-community.slack.com/archives/C012RBZFMDG/p1639429238101900
- https://ory-community.slack.com/archives/C012RBZFMDG/p1639455679103600

### Version

0.6.7

### On which operating system are you observing this issue?

macOS

### In which environment are you deploying?

Kubernetes with Helm

**Comment by zepatrik** [comment]
The part about pagination is clear.
However, what I don't get is how the permissions could change. Does the subject in fact have that permission? Is it just not initially displayed? The default page size is ~100 iirc, so getting 30 items should not be a problem. Maybe you could give the raw responses to see how the list changes?
The pages themselves should be ordered btw, don't think that is the problem: https://github.com/ory/keto/blob/master/internal/persistence/sql/relationtuples.go#L215
