### ISSUE TITLE
Unable to initialize compiler: lstat /build: no such file or directory

### ISSUE THREAD

**Issue by ingenieroariel** [ory/keto#81]
**Describe the bug**
keto serve does not start

**To Reproduce**
1. keto serve
Unable to initialize compiler: lstat /build: no such file or directory

**Expected behavior**
The server running

**Version:**
 - Environment: [Nixos]
 - Version [7798442553cfe7989a23d2c389c8c63a24013543]

**Additional context**
I am writing a nixos service for ORY, was already successful in creating one for Hydra and Oathkeeper but ran into this, that looks like https://github.com/ory/keto/issues/73

**Comment by ingenieroariel** [comment]
I was able to avoid the segfault by replacing the relative url with an absolute one in my system.

I could not get packr to work on nix, but this workaround stops keto serve from dying early in the process.

```
diff --git a/cmd/server/serve.go b/cmd/server/serve.go
index 4190b71..f324743 100644
--- a/cmd/server/serve.go
+++ b/cmd/server/serve.go
@@ -57,10 +57,10 @@ func RunServe(
        buildVersion, buildHash string, buildTime string,
 ) func(cmd *cobra.Command, args []string) {
        return func(cmd *cobra.Command, args []string) {
-               box := packr.NewBox("../../engine/ladon/rego")
+               box := packr.NewBox("/x/rego")
 
                compiler, err := engine.NewCompiler(box, logger)
-               cmdx.Must(err, "Unable to initialize compiler: %s", err)
+               cmdx.Must(err, "Ariel Unable to initialize compiler: %s", err)
 
                writer := herodot.NewJSONWriter(logger)
                //writer.ErrorEnhancer = nil
```

refs #79

**Comment by aeneasr** [comment]
closing in favor of #73
