### ISSUE TITLE
Conditional function based on Context Conditions does not Apply

### ISSUE THREAD

**Issue by ppvolto** [ory/keto#82]
**Bug or Unclear Documentation**
Conditional function based on Context Conditions does not Apply
Tested with `EqualsSubjectCondition` and `StringEqualCondition`  

**To Reproduce**
1. Create a exact Policie with the resulting Json Response on: /engines/acp/ory/exact/policies
```json
[{
   "id": "test-users-alice",
   "description": "",
   "subjects": ["users:alice"],
   "resources": ["resources:users:alice"],
   "actions": [ "read", "update"],
   "effect": "allow",
   "conditions": [ {
      "subject": {
         "type": "EqualsSubjectCondition"
      }
   }]
}]
```
2. Request on /engines/acp/ory/exact/allowed with the Request Body:
```json
{
    "action": "read",
    "subject": "users:alice",
    "resource": "resources:users:alice",
    "context": {
        "subject": "users:alice"
    }
}
```
3. Results in following Result
```json
{
    "allowed": false
}
```

**Expected behavior**
Expected is to following Result:
```json
{
    "allowed": true
}
```

**Version:**
 - Environment: Docker
 - Version: oryd/keto:v0.2.2-sandbox_oryOS.10

**Comment by aeneasr** [comment]
That's definitely a bug, would you mind throwing up a PR with a breaking test?

**Comment by minchao** [comment]
I found that the conditions is an array in the swagger spec, but in the condition.rego it is not.

See:

https://github.com/ory/keto/blob/18e3f84cdeee317f942d61753399675c98886e5d/docs/api.swagger.json#L897-L899

https://github.com/ory/keto/blob/ee9bcf2719178e5a8dccca083a90313947a8a63b/engine/ladon/rego/condition/condition.rego#L7-L10

**Comment by aeneasr** [comment]
Oh right, it certainly isn't an array but a keyed object!

**Comment by aeneasr** [comment]
Right, that seems to be the problem here

**Comment by JesusIslam** [comment]
I also got hit by this problem. Wasted an hour finding out if my policies are wrong, my roles are wrong, or my requests are wrong. Opened the issue page and here I am.

I use Keto version `v0.2.3-sandbox_oryOS.10`

**Comment by minchao** [comment]
@JesusIslam 

A quick fix:

Remove the `[]` below, and build your own docker image. You also need to update api.swagger.json and SDKs if needed.

https://github.com/ory/keto/blob/18e3f84cdeee317f942d61753399675c98886e5d/engine/ladon/policy.go#L49

**Comment by aeneasr** [comment]
Yeah sorry about that, feel free to throw up a PR!

**Comment by JesusIslam** [comment]
> @JesusIslam
> 
> A quick fix:
> 
> Remove the `[]` below, and build your own docker image. You also need to update api.swagger.json and SDKs if needed.
> 
> [keto/engine/ladon/policy.go](https://github.com/ory/keto/blob/18e3f84cdeee317f942d61753399675c98886e5d/engine/ladon/policy.go#L49)
> 
> Line 49 in [18e3f84](/ory/keto/commit/18e3f84cdeee317f942d61753399675c98886e5d)
> 
>  Conditions []map[string]interface{} `json:"conditions"`

Thanks, that's what I am gonna do for now.

@aeneasr thanks for confirming this problem.

**Comment by aeneasr** [comment]
Fixed by #86

**Comment by asdptkt** [comment]
The unstable tag from docker repository seems to be still affected by this bug.

**Comment by minchao** [comment]
@asdptkt EqualsSubjectCondition include an empty options object. See: https://www.ory.sh/docs/next/keto/engines/acp-ory#subject-condition

**Comment by asdptkt** [comment]
@minchao oh, I forgot to mention that it's not `EqualsSubjectCondition` that did this, that works fine. It is `StringMatchCondition` that shows this behavior. This is my policy, "admin" subject here is a role:

```
[
    {
        "id": "test:admin",
        "description": "test admin",
        "subjects": [
            "admin"
        ],
        "actions": [
            "get",
            "create",
            "delete",
            "update",
            "subscribe",
            "publish",
            "super"
        ],
        "effect": "allow",
        "resources": [
            "<.*>"
        ],
        "conditions": {
            "status": {
                "type": "StringMatchCondition",
                "options": {
                    "equals": "^active$"
                }
            }
        }
    }
]
```

This is my request to `/engines/acp/ory/regex/allowed`:

```
{
  "action": "get",
  "context": {
    "status": "active"
  },
  "resource": "test",
  "subject": "01D2HH6K3Q83YSD9MAZTJDBRA1"
}
```

Should I create a new issue?

**Comment by minchao** [comment]
@asdptkt Thank you for your supplement explanation.

@aeneasr In the code below, that use `options.matches` for StringMatchCondition, but the [doc](https://www.ory.sh/docs/next/keto/engines/acp-ory#string-match-condition) is `options.equals`.

https://github.com/ory/keto/blob/39a1486dc53456189d30380460a9aeba198fa9e9/engine/ladon/rego/condition/string_match.rego#L4

**Comment by asdptkt** [comment]
Hi @minchao, thank's for the help. I just change `equals` to `matches` and it instantly worked. So it's just the matter of wrong documentations it seems.
