### ISSUE TITLE
Upgrade deprecated `grpc-tools` to `@grpc/grpc-js`

### ISSUE THREAD

**Issue by aeneasr** [ory/keto#835]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

grpc-tools does not work with Apple M1 as darwin arm64 binaries are missing, thus it is not possible to run tasks like `make buf` on an Apple M1 chip.

grpc-tools is deprectead, and maintainers encourage to use `@grpc/grpc-js` instead.

### Reproducing the bug

See above

### Version

master

**Comment by zepatrik** [comment]
`grpc-tools` is not deprecated and does something completely different than `@grpc/grpc-js`. We already use `@grpc/grpc-js` instead of the deprecated `grpc` package.
However, I overhauled and upgraded the buf and protoc pipeline in #1097. I hope that works on apple arm chips now.

**Comment by zepatrik** [comment]
The new version should work on mac/arm https://github.com/grpc/grpc-node/issues/1405#issuecomment-1268791265 outside of docker at least.
