### ISSUE TITLE
question: performance & benchmarks

### ISSUE THREAD

**Issue by mailaneel** [ory/keto#89]
Would you be able to provide some insight into performace implications of switching to OPA based implementation. I saw in the original PR that says we have 10x improvement for simple cases

Some questions I have are..
- how many queries / data loaded per evaluate request
- do we load all collections data for every query? if so what is the better way to do resouce level permissions / field level permissions
- Is there a way to add cache at some level

**Comment by aeneasr** [comment]
Good questions, for most of your answers please take a look at the code! Regarding the original benchmarks, they were internal and not tidied up which is why they are not available publicly. Your questions also depend on OPA internals in part.

**Comment by mailaneel** [comment]
this is my understanding by looking at below 2 lines of code, I could be completely wrong
 https://github.com/ory/keto/blob/1cb8a36a08883b785d9bb0a4be1ddc00f1f9d358/engine/ladon/handler.go#L482

https://github.com/ory/keto/blob/1cb8a36a08883b785d9bb0a4be1ddc00f1f9d358/storage/manager_sql.go#L161


- It looks to me that we are loading all policies and roles of particular flavour
- And query is made every time there is call to `/allowed` endpoint

Example use cases:
1. Ability for user to give access to a third party for their resources 

```json
{
	"subjects": ["alice"],
	"resources": ["users:bob:accounts:2"],
	"actions": ["accounts:read"],
	"effect": "allow"
}
```

2. May be only allow some fields on the account

```json
{
	"subjects": ["alice"],
	"resources": ["users:bob:accounts:2", "users:bob:accounts:2:fields:name,balance"],
	"actions": ["accounts:read"],
	"effect": "allow"
}
```

3. Ability to control based on tenant

```json
resources:myorg.com:tenants:<tenant-id>:<resource-id>
```


The reason for me to ask above questions is to better understand how to structure policies and how much data we can save before it becomes a bottle neck.

- How many policy objects can we have before we hit bottle neck
- How many role object can we have before we hit bottle neck


Appreciate your guidance on this. Thanks

**Comment by aeneasr** [comment]
Yeah, that's how OPA works unless we write a custom storage adapter. The idea for OPA really is to have all of this stuff available in memory, otherwise it can't reach a proper conclusion. It's also much better to have it in memory as the real bottleneck is stuff such as `SELECT * FROM regexp_match(...)` which can't use indices and is thus painfully slow. That's also why we switched to OPA/in-memory because the SQL adapter there didn't scale above ~50k policies.
