### ISSUE TITLE
Deleting a namespace that contains relation tuples results in GetRelationTuples returning "not found"

### ISSUE THREAD

**Issue by hperl** [ory/keto#946]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [X] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [X] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

When I delete a namespace that has relation tuples, subsequent calls to GetRelationTuples returns in a "not found" (for the deleted namespace).

Instead, GetRelationTuples should just filter out the tuples for which the namespace was deleted.

### Reproducing the bug

1. Create namespace "users"
2. Create relation tuple "users:foo#id@123"
3. Delete namespace "users"
4. GetRelationTuples

--> Throws "not found"

### Version

v0.8.0

**Comment by aeneasr** [comment]
Isn't 404 the expected result here, since the namespace no longer exists?
