### ISSUE TITLE
Swagger route mismatch vs docs - /admin/relation-tuples vs /relation-tuples

### ISSUE THREAD

**Issue by KevinBarbier2** [ory/keto#968]
### Preflight checklist

- [X] I could not find a solution in the existing issues, docs, nor discussions.
- [X] I agree to follow this project's [Code of Conduct](https://github.com/ory/keto/blob/master/CODE_OF_CONDUCT.md).
- [X] I have read and am following this repository's [Contribution Guidelines](https://github.com/ory/keto/blob/master/CONTRIBUTING.md).
- [ ] This issue affects my [Ory Cloud](https://www.ory.sh/) project.
- [ ] I have joined the [Ory Community Slack](https://slack.ory.sh).
- [ ] I am signed up to the [Ory Security Patch Newsletter](https://ory.us10.list-manage.com/subscribe?u=ffb1a878e4ec6c0ed312a3480&id=f605a41b53).

### Describe the bug

https://github.com/ory/keto/blob/master/spec/swagger.json#L22

swagger for Keto has `/admin` prefixed on the relation-tuples write routes for PUT PATCH and DELETE

Keto doesn't seem to have such routes, calling PUT `/admin/relation-tuples` returns a 404.

Jul 28 13:17:40 keto[234651]: {"http_request":{"headers":{"accept":"application/json","content-length":"79","content-type":"application/json","user-agent":"curl/7.61.1"},"host":"127.0.0.1:4446","method":"PUT","path":"/admin/relation-tuples","query":null,"remote":"127.0.0.1:54626","scheme":"http"},"http_response":{"headers":{"content-type":"text/plain; charset=utf-8","x-content-type-options":"nosniff"},"size":19,**"status":404**,"text_status":"Not Found","took":116440},"level":"info","msg":"completed handling request","time":"2022-07-28T13:17:40Z"}

Furthermore, calling PUT ` /relation-tuples` also returns `Method not allowed`

`curl -X 'PUT' 'http://127.0.0.1:4446/relation-tuples' -d '{"namespace": "test","object": "test","relation": "read","subject_id": "test"}'`
`Method Not Allowed`

I see do not see a http method allow list, only for cors, which shouldnt have effect on a curl request and has PUT allowed by default. Why is Keto blocking PUT, is this also different from the documentation?

### Reproducing the bug

Load the swagger.json from spec into swagger-ui and create a relation-tuple on the swagger route /admin/relation-tuples which returns a 404 Not found.

### Relevant configuration

```yml
dsn: postgres://xxxxxxxxxxxxxxxxxxx
log:
  format: json
  leak_sensitive_values: false
  level: info
serve:
  write:
    host: 127.0.0.1
    port: 4446
  read:
    host: 127.0.0.1
    port: 4446
```

### Version

v0.8.0-alpha.2

### On which operating system are you observing this issue?

Linux

### In which environment are you deploying?

Binary

**Comment by zepatrik** [comment]
Yes, master and `v0.8.0-alpha.2` are not the same versions. Please use https://github.com/ory/keto/blob/v0.8.0-alpha.2/spec/swagger.json instead.
